### ISSUE TITLE
Shortcut keys ('j' and 'k') do not obey the ordered list

### ISSUE THREAD

**Issue by Ack0** [soufianesakhi/feedly-filtering-and-sorting#1]
The keys "j" and "k" do not open the correct items in an ordered list. Can you fix it? Thanks in advance.

**Comment by soufianesakhi** [comment]
Hello,
I'll look into this issue as soon as possible

**Comment by soufianesakhi** [comment]
Hello, this issue is fixed in the [1.5.3](https://github.com/soufianesakhi/feedly-filtering-and-sorting/releases/tag/1.5.3) version. Enjoy :)
