### ISSUE TITLE
Bug(?): After the list is sorted, the page is not going to the top

### ISSUE THREAD

**Issue by Ack0** [soufianesakhi/feedly-filtering-and-sorting#10]
Hi!

Should not the page go to the top after the list is sorted?

Thanks in advance!

**Comment by soufianesakhi** [comment]
You mean when auto loading all unread articles, the page is stuck at the bottom when trying to load more ?
If yes then one of these requirements are not met:
- The `Unread Only` option is required to be enabled.
- Additionally the `Latest` sort option must be enabled to use sorting functionality

![Feedly settings](https://raw.githubusercontent.com/soufianesakhi/feedly-filtering-and-sorting/master/screenshots/feedly_settings.PNG)

**Comment by Ack0** [comment]
Yes, Latest+Unread Only are checked, but after load all articles the page isn't going to the top.

**Comment by soufianesakhi** [comment]
does it load all the entries then get stuck at bottom ? If so, can you see the giant mark as read button ?
If not, can you see any particular errors in the console log ?
thanks

**Comment by Ack0** [comment]
> does it load all the entries then get stuck at bottom ?

Yes.

> If so, can you see the giant mark as read button ?

No, just ``END OF FEED`` text.

> If not, can you see any particular errors in the console log ?

Just this:
``
VM770:2025 Feedly page fully loaded
``
``
VM770:615 Loaded saved subscription: {"filteringEnabled":false,"restrictingEnabled":false,"sortingEnabled":true,"openAndMarkAsRead":true,"markAsReadAboveBelow":true,"hideWhenMarkAboveBelow":false,"hideAfterRead":false,"sortingType":0,"advancedControlsReceivedPeriod":{"maxHours":6,"keepUnread":false,"hide":false,"showIfHot":false,"minPopularity":200,"markAsReadVisible":false},"pinHotToTop":false,"additionalSortingTypes":["0","6","3","5"],"filteringListsByType":{"0":[],"1":[]},"keywordMatchingAreas":[0],"alwaysUseDefaultMatchingAreas":true,"keywordMatchingMethod":0,"url":"---global settings---"}
``

**Comment by soufianesakhi** [comment]
I see the problem now.
I didn't know the `Giant Mark As Read` can be disabled.
I will write a fix

**Comment by soufianesakhi** [comment]
Issue fixed in v2.5.1 :)
