### ISSUE TITLE
Articles disappearing on click, buttons appearing multiple times

### ISSUE THREAD

**Issue by saputnik** [soufianesakhi/feedly-filtering-and-sorting#102]
I think I found another issue (I am using 3.20.1), I don't know if it's only me. When I click on an article it disappears immediately, see video recording

https://user-images.githubusercontent.com/48006970/117631297-63998a80-b17c-11eb-90c7-910fa80d0a08.mov

**Comment by johnpane** [comment]
Also, I commented in the prior issue after it was closed, that filtered articles are hidden but are still being presented when I navigate with the "j" key.

**Comment by soufianesakhi** [comment]
I have released a new version that should fix most issues.
