### ISSUE TITLE
Doesn't work on Leo priority pages

### ISSUE THREAD

**Issue by tsitelov** [soufianesakhi/feedly-filtering-and-sorting#103]
When I open a Leo priority list with the plugin enabled, sorting of loaded articles seems working, but then clicking 'j' opens some article in the middle of the list, attempt to click on the top article shows Feedly diagnostic message "An unexpected error occurred"

**Comment by soufianesakhi** [comment]
Hello, this is normal as it's not currently supported. The extension is not compatible with premium features.

**Comment by tsitelov** [comment]
Well, it's a pity to hear this, because I cannot use extension even with "normal" interfaces because it makes premium interfaces unusable. Is it possible to make the extension not interfere with premium interfaces, but work as usual with common interfaces?

**Comment by soufianesakhi** [comment]
If you send me some URLs for the premium pages, I can disable them sure

**Comment by tsitelov** [comment]
Standalone LEO PRIORITIES section links have the following pattern:

```
https://feedly.com/i/priority/content/user/<user-id>/priority/<list-id>
```

Example (slightly obfuscated with xxx/yyy):
```
https://feedly.com/i/priority/content/user/f6e5daf3-8cc5-49a0-8d4e-xxxxxxxxxxxx/priority/6561fb5f-80c4-49bc-8c74-yyyyyyyyyy
https://feedly.com/i/priority/content/user/f6e5daf3-8cc5-49a0-8d4e-xxxxxxxxxxxx/priority/55f8a664-d80d-427d-aa9a-yyyyyyyyyy
```

**Comment by soufianesakhi** [comment]
Can you check if it's fixed in v3.20.5?

**Comment by tsitelov** [comment]
Standalone priority pages look fine (without additional plugin features, as expected) - thank you.

Unfortunately, plugin sorting also disappeared on priority tabs associated with categories, that have a different pattern:

```
https://feedly.com/i/collection/priority/user/<user-id>/category/<category-id>
```
Example:

```
https://feedly.com/i/collection/priority/user/f6e5daf3-8cc5-49a0-xxxxxxxxxxxx/category/news
```

I consider it as a slight degradation because all plugin features were working on that pages before the update without any problems.

**Comment by soufianesakhi** [comment]
Thanks for your response.
I only support free features, the extension is now disabled on all other pages.
