### ISSUE TITLE
Lingering problems in 3.20.2

### ISSUE THREAD

**Issue by johnpane** [soufianesakhi/feedly-filtering-and-sorting#104]
Something seems wrong with the linkage between articles. Navigating with the j and k keys does not always flow linearly and sometimes skips articles. Departing from an article sometimes moves its placement in the list -- for example, navigating away from the first article in the list might move it to the end of the list. Sometimes when repeatedly selecting the j key, the same article comes up multiple times while other articles are not opened.

The check-mark buttons for marking read/unread are present when articles are shown on one line, but when an article is open the buttons are absent from their usual place among the built-in feedly buttons. Pressing the button does not always act on all of the articles above or below the current one. For example, if I click the √^ button on the last article in the list, it marks all as unread except the current article and the first in the list. Similarly, if I click √v on the first article in the list it leaves the last article in the list unchanged.

**Comment by soufianesakhi** [comment]
Can you check if it's fixed in v3.20.5?

**Comment by johnpane** [comment]
Yes, these appear to be fixed now, thank you.

However, your changes in response to issue #79 are no longer working.

**Comment by soufianesakhi** [comment]
I have disabled the extension on pages that are not supported and restored the default behavior for the mark as read on "All" page as requested by other users for now

**Comment by johnpane** [comment]
Just to be clear, #79 was not about "mark as read" but simply navigating with shift-J from All and Today pages.

**Comment by soufianesakhi** [comment]
Yes I understand, I will see how I can implement it in the future
