### ISSUE TITLE
Displaced icon "Read Later"

### ISSUE THREAD

**Issue by Detsle** [soufianesakhi/feedly-filtering-and-sorting#105]
In all sections, the icon is displayed correctly, except for the section "Read later"

![screen](https://user-images.githubusercontent.com/22348086/118128645-d8322a80-b403-11eb-806e-acd82cc46bb3.png)

**Comment by soufianesakhi** [comment]
Can you check if it's fixed in v3.20.5?

**Comment by Detsle** [comment]
Now the icon is completely gone.

![image](https://user-images.githubusercontent.com/22348086/118345543-e84e2500-b53d-11eb-94a5-5c045130dac0.png)

**Comment by soufianesakhi** [comment]
This is something expected as the read later page is not supported
