### ISSUE TITLE
navigation issues have re-appeared

### ISSUE THREAD

**Issue by johnpane** [soufianesakhi/feedly-filtering-and-sorting#106]
Navigation problems again. The attached short video shows pressing the n and p keys -- it skips the middle article. This does not happen when FFnS is not running.

I am so sorry to keep reporting issues. Feedly itself must be undergoing a lot of change. Your software and efforts to maintain it are greatly appreciated!

https://user-images.githubusercontent.com/14841761/118682139-2a8d9580-b7ce-11eb-9992-b61865a02704.mov

**Comment by soufianesakhi** [comment]
Do you still have this problem? I have tried reproducing the issue for weeks without success.
If so can you send me your settings export via email: soufiane.sakhi.js@gmail.com

**Comment by johnpane** [comment]
This problem has not been happening lately. I will let you know if it comes back. Thank you.
