### ISSUE TITLE
Popular articles

### ISSUE THREAD

**Issue by saputnik** [soufianesakhi/feedly-filtering-and-sorting#107]
Hey! Maybe it's not related to the extension but since a couple of days I don't get any article with popularity inferior to 100. Is it only me or Feedly changed something?

<img width="192" alt="Screen Shot 2021-05-27 at 16 19 18" src="https://user-images.githubusercontent.com/48006970/119843124-890dee80-bf07-11eb-9242-871adf9c4393.png">

**Comment by saputnik** [comment]
Before I was getting in the list also articles with just 20+

**Comment by soufianesakhi** [comment]
Can you disable the extension and check if there is the same number of articles?

**Comment by saputnik** [comment]
I did, I think Feedly changed some settings, it's not related to the extension...

<img width="743" alt="Screen Shot 2021-05-27 at 23 21 41" src="https://user-images.githubusercontent.com/48006970/119898615-5f25ed80-bf42-11eb-9ac9-ffc120b332a9.png">
<img width="732" alt="Screen Shot 2021-05-27 at 23 21 28" src="https://user-images.githubusercontent.com/48006970/119898620-60571a80-bf42-11eb-8265-f7086034d70b.png">

**Comment by saputnik** [comment]
I wrote to Feedly to check if there was any change, I will let you know. And thank for everything!

**Comment by saputnik** [comment]
They said "no change on our side as far as I know. "

It might be related to the extension. I just added a source now and I see articles with lower popularity before adding it to feedly

<img width="324" alt="Screen Shot 2021-05-28 at 09 33 16" src="https://user-images.githubusercontent.com/48006970/119947315-e8b3da80-bf97-11eb-8509-90d12a555c84.png">

**Comment by saputnik** [comment]
Same with this new source. Before adding it to Feedly I see articles with lower popularity, after adding it they disappear 
<img width="805" alt="Screen Shot 2021-05-28 at 09 53 44" src="https://user-images.githubusercontent.com/48006970/119949976-b22b8f00-bf9a-11eb-9ade-2ae09fe43bae.png">

**Comment by soufianesakhi** [comment]
Can you send me your settings export via email: soufiane.sakhi.js@gmail.com

**Comment by saputnik** [comment]
done! thanks!

**Comment by soufianesakhi** [comment]
You have enabled in Advanced controls > Recently received articles the "Hidden" option, which will hide all recent articles (1 day and 12 hours in your case) unless they are popular (popularity superior to 5 in your case).
You can uncheck this option if you are not using it

**Comment by saputnik** [comment]
done. i am just puzzled because earlier I could see articles with lower popularity (like 20, 30, etc.), but that’s not the case since a while. maybe it’s related to feedly, not to the extension

**Comment by saputnik** [comment]
Now everything works again as before

<img width="272" alt="Screen Shot 2021-06-11 at 19 27 21" src="https://user-images.githubusercontent.com/48006970/121726650-231a8d00-caeb-11eb-84b5-4d62d8daf9ef.png">
