### ISSUE TITLE
The extension icon disappeared from feedly.com

### ISSUE THREAD

**Issue by Detsle** [soufianesakhi/feedly-filtering-and-sorting#108]
![image](https://user-images.githubusercontent.com/22348086/121132519-eb38ee80-c839-11eb-86ca-5d621cf8773e.png)
After updating the extension, there is no icon at all.

**Comment by soufianesakhi** [comment]
I am unable to reproduce.
Can do you use the extension or the script?
What are the versions of your browser and operating system?
Is it on all pages or just specific Feedly pages?

**Comment by Detsle** [comment]
Used https://chrome.google.com/webstore/detail/feedly-filtering-and-sort/anknmaofbemimfabppdffklbfiecikgo
Chromium 86.0.4240.198 and Windows 10
All pages

**Comment by Detsle** [comment]
During the last update, everything was fine.

**Comment by soufianesakhi** [comment]
Can you check the logs and search for any errors and copy them here?

**Comment by Detsle** [comment]
Where can I find them?

**Comment by soufianesakhi** [comment]
CTRL + SHIFT + I , Console tab

**Comment by Detsle** [comment]
[feedly.com-1623445101041.log](https://github.com/soufianesakhi/feedly-filtering-and-sorting/files/6640969/feedly.com-1623445101041.log)

**Comment by soufianesakhi** [comment]
Can you disable your adblocker and reload the page?

**Comment by Detsle** [comment]
Yes, I did that too, the result is the same.

**Comment by soufianesakhi** [comment]
In the Console, do you have any result when you execute: `document.querySelector("body .ShowSettingsBtn")`

**Comment by Detsle** [comment]
Do I understand correctly, turn off all blockers and check the console?

**Comment by soufianesakhi** [comment]
Just the console (you can leave blockers on), paste the command at the bottom input field and press ENTER, and tell me what are the results of this command

**Comment by Detsle** [comment]
document.querySelector("body .ShowSettingsBtn")
null

**Comment by soufianesakhi** [comment]
Are you sure the extension is not disabled? Can you try the [script ](https://github.com/soufianesakhi/feedly-filtering-and-sorting#install-as-a-user-script) instead (with [Tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=en))

**Comment by Detsle** [comment]
![image](https://user-images.githubusercontent.com/22348086/121750415-02ffc380-cb15-11eb-9202-86ee934b623e.png)
The extension does not work, and the script starts immediately.

**Comment by soufianesakhi** [comment]
What's the issue with the script? Can you give me the logs from the console (select all the output, scroll down if necessary)

**Comment by Detsle** [comment]
Where can I find them?

**Comment by soufianesakhi** [comment]
Same as before (CTRL + SHIFT + I , Console tab)

**Comment by Detsle** [comment]
Only do it with a script?
No extension, right?

**Comment by Detsle** [comment]
![image](https://user-images.githubusercontent.com/22348086/121751192-5b839080-cb16-11eb-8913-ffd6b77002b9.png)
[feedly.com-1623447452827.log](https://github.com/soufianesakhi/feedly-filtering-and-sorting/files/6641070/feedly.com-1623447452827.log)

document.querySelector("body .ShowSettingsBtn")
button.ShowSettingsBtn

**Comment by soufianesakhi** [comment]
there is still no button with the script? are you a pro user?

**Comment by Detsle** [comment]
The script works as I told you earlier.
The extension doesn't work.
When the script is enabled, the button is there.
No, I'm a free user.

**Comment by soufianesakhi** [comment]
Maybe it's an issue with Chromium, can you upgrade to the latest version? I only support Google Chrome and Firefox at the time being, not tested with other browsers

**Comment by Detsle** [comment]
Chromium is like the engine of Google Chrome. Now I downloaded the latest version of the portable browser, everything works in it.
Is it possible to somehow make the extension work on an older version of Chrome?

**Comment by Detsle** [comment]
3.21.1 worked correctly on the old version of the browser.

**Comment by soufianesakhi** [comment]
I have upgraded recently to ECMAScript 2020, this is definitely the cause of your problem.
It makes it easier to develop and support the extension.
I strongly encourage you to upgrade your browser as you will also benefit from security patches.
