### ISSUE TITLE
Shortcuts don't work

### ISSUE THREAD

**Issue by carlosmg2** [soufianesakhi/feedly-filtering-and-sorting#109]
If I have this script enabled shortcuts 'J' / 'K' to jump to next/previous article don't work on Feedly

**Comment by johnpane** [comment]
I am also seeing navigation issues today.

**Comment by ms6666** [comment]
Same here, no sorting, no navigation

**Comment by soufianesakhi** [comment]
Hello, thanks for opening the issue, I am looking for a fix.
If your experiencing any other problem not relating to the current issue, please open a a new issue

**Comment by soufianesakhi** [comment]
Hello, thanks for opening the issue, I am looking for a fix.
If you're experiencing any other problem not relating to the current issue, please open a new issue

**Comment by soufianesakhi** [comment]
This is now fixed in the latest version
