### ISSUE TITLE
Is the mark as read on scroll bugged ?

### ISSUE THREAD

**Issue by GokuderaElPsyCongroo** [soufianesakhi/feedly-filtering-and-sorting#11]
Hello, thank you very much for implementing the hiding feature, it's greatly useful. I was wondering if there is a bug on the native mark as read on scroll ? When the list is sorted by popularity, scrolling marks as read not just one but several articles at once ; while when it's sorted by publish date it works fine. When sorted by popularity, does feedly still consider that the list is sorted by publish date ? Thanks again for all your work.

Edit: is there a way to prevent all articles from scrolling up when hiding a single article ? That would look disgraceful, a gap in the middle of the list, and I don't know if it's even possible, but that way coupling the "mark as read on scroll" feature and the "hide articles after reading" one you implemented would prevent several articles from behind marked as read. But thats probably not possible since I don't understand how articles would load after that…
My wish is to be able to mark as read articles on scroll and hide them doing that. Doing that when all unread articles are loaded is possible, but it's impossible to use the "auto load all unread articles" feature when the "mark as read on scroll" one is activated, since it will mark everything as read. Maybe using a shortcut to toggle the mark as read on scroll feature ? So all I'll have to do is deactivate it while all articles are loading and reactivate it after ? Or by finding a way to load articles in the background, without making the page scrolling ?… I don't know anything about coding and I know it's hard.

Sorry to be such a bother, I have so much articles to read that I want to be able to look through them as quickly as possible. Your script is great.

**Comment by soufianesakhi** [comment]
Hello, from what I understood, you want to:
- Add support to mark as read on scroll: not currently supported, so I will have to tweak feedly to supplement the sorted list (Needs time)
- Prevent scroll when hiding articles: maybe can be implemented by adding a gap the size of the hidden article to the beginning ? I'll think about it
- Load articles in the background, without making the page scrolling: this seems like a nice idea, definitely in my backlog
Thanks for your ideas :)

**Comment by GokuderaElPsyCongroo** [comment]
Hello, also if it's not too time consuming, could it be possible to add an option to fuse the "mark previous as read and hide" and "open articles in a new window/tab" features ? That would save some clicks to browse the list and read articles I think. Thanks very much for your work.

**Comment by soufianesakhi** [comment]
Two of your requests has been implemented in v2.6.1.
Can you create another issue to explain the remaining wishes ? thanks
