### ISSUE TITLE
Mark read buttons disappeared

### ISSUE THREAD

**Issue by mael2** [soufianesakhi/feedly-filtering-and-sorting#111]
"Add buttons to mark articles above/below as (read)" doesn't work anymore, the buttons are missing.
I'm using Version 3.21.6

Would you check if they can be fixed, please?

Thank you very much!

**Comment by johnpane** [comment]
Same for me.

**Comment by soufianesakhi** [comment]
Hello, the buttons were missing in the Article view.
This is now fixed in v3.21.7
