### ISSUE TITLE
Filtering not working

### ISSUE THREAD

**Issue by johnpane** [soufianesakhi/feedly-filtering-and-sorting#112]
The list of unread articles displays the filtered results, but navigating through with the j and k keys displays all articles, even those that were filtered out.

**Comment by soufianesakhi** [comment]
Hello, I really tried but couldn't reproduce these problems.
Can you send me your extension settings, the layout that you use (title/card/magazine/article), a feed url example and any other Feedly settings that can be relevant ?

**Comment by saputnik** [comment]
my apologies, after couple of hours everything started to work again as before, no idea what happened….

**Comment by johnpane** [comment]
Yes, here are the requested files. 

1. opml file with one feed that exhibits the problem (many others also show the same problem)
[03. corner.opml.txt](https://github.com/soufianesakhi/feedly-filtering-and-sorting/files/7576777/03.corner.opml.txt)

2. extension settings
[feedly-filtering-and-sorting.json.txt](https://github.com/soufianesakhi/feedly-filtering-and-sorting/files/7576778/feedly-filtering-and-sorting.json.txt)

3. screen shot of relevant feedly settings
<img width="648" alt="Screen Shot 2021-11-21 at 12 54 01" src="https://user-images.githubusercontent.com/14841761/142773472-994c61bf-525c-4bb2-b794-29298e81e861.png">

Thank you!
John

**Comment by johnpane** [comment]
Your latest commit helped the problem somewhat.

I still have problems if I enter a new feed and navigate to the first article too quickly (j key). It briefly shows the article then the whole list is refreshed -- the one I was looking at is no longer on the list because it has now been read. Thus, I do not have enough time to read that one. 

This may be related to a delay that you added in an earlier commit.

**Comment by soufianesakhi** [comment]
Can you test v3.21.10?

**Comment by saputnik** [comment]
everything fine :)

**Comment by johnpane** [comment]
It is working much better. 

Now to break it I have to hit "j" very quickly after entering the feed. A more natural pause before hitting "j" and it works correctly.

When I hit "j" too soon, the chosen article appears and immediately disappears. It also seems to break the linkages between articles so they are not ordered correctly and may not all be linked in a linear list. My guess is that there is a race condition in FFnS sorting and the data structure is being rewritten after I have already entered into an article, caching invalid data.

**Comment by soufianesakhi** [comment]
Thanks for your response.
While articles are still loading, you can't navigate until it's finished as sorting is being run.
Feel free to open a new issue if you see other issues relating to this.

**Comment by johnpane** [comment]
Thank you!
