### ISSUE TITLE
Ranking

### ISSUE THREAD

**Issue by saputnik** [soufianesakhi/feedly-filtering-and-sorting#116]
My apologies, but I have again some issue... the ranking of the articles doesn't work since couple of days, see screenshot. Sorry for bothering so much.
<img width="401" alt="Screenshot 2021-12-01 at 08 50 02" src="https://user-images.githubusercontent.com/48006970/144206226-39cf1a4b-9515-432f-b212-589383201bf4.png">
..

**Comment by saputnik** [comment]
it happens constantl
<img width="767" alt="Screenshot 2021-12-01 at 11 03 22" src="https://user-images.githubusercontent.com/48006970/144214034-67c6eb2d-e32f-49a6-99d1-0630f46c1773.png">
y

**Comment by saputnik** [comment]
with 3.21.11 seems to be working again, just testing right now (THANKS!)
<img width="379" alt="Screenshot 2021-12-02 at 11 44 32" src="https://user-images.githubusercontent.com/48006970/144407158-07f94930-6c8f-4117-b933-74144d1873f9.png">

**Comment by soufianesakhi** [comment]
Fixed in v3.21.11
