### ISSUE TITLE
Articles disappearing on entry

### ISSUE THREAD

**Issue by johnpane** [soufianesakhi/feedly-filtering-and-sorting#117]
Unfortunately, I am still having problems with articles disappearing when I try to read them. This occurs even if I wait a long time for things to settle before starting to navigate. In the screen shot I show mouse clicks but this also happens when navigating with the "j" key. At the end of the recording I accidentally hit "esc" and a fourth article appeared in the list.

https://user-images.githubusercontent.com/14841761/144413851-ae85e2fc-f6f1-49cc-a58e-f896b329f1bd.mov

**Comment by johnpane** [comment]
I am sorting by publish date. If I turn off sorting the problem does not occur.

**Comment by soufianesakhi** [comment]
Some fixes regarding this were implemented in v3.21.12, but keep in mind that if "Auto load all unread articles" is disabled, feedly will load more articles before reaching the end of the list, and additional sorting will occur, so the article should be reselected.

Also if you sort by x date (new first), Feedly sorting should be set to "Latest", else when sorting by x date (old first), Feedly sorting should be set to "Oldest".

**Comment by johnpane** [comment]
Thank you as always!
