### ISSUE TITLE
Settings and buttons have disappeared from Today page

### ISSUE THREAD

**Issue by MousElPsyCongroo** [soufianesakhi/feedly-filtering-and-sorting#119]
Using pro, not sure if it has an impact. All page works correctly.

Thanks!

![feedly_today](https://user-images.githubusercontent.com/92920928/146649518-a25316b0-4eaa-4117-bfb3-c01b1f854307.png)

**Comment by soufianesakhi** [comment]
Hello, this is normal, the Today page is no longer supported

**Comment by MousElPsyCongroo** [comment]
Not sure if only having the click to open in new tab feature, or only the feature I just requested (n/p shortcut on edges click) on the Today page would cause bugs too?

**Comment by soufianesakhi** [comment]
All features are not supported on this page
