### ISSUE TITLE
Gap when hiding articles, received date in advanced controls

### ISSUE THREAD

**Issue by GokuderaElPsyCongroo** [soufianesakhi/feedly-filtering-and-sorting#12]
Hello, thank you very much for taking the time to implement those features, your work is great. I'm currently testing it, the auto loading works but it seems like changing the batch size has no effect ? Maybe it's because I have A LOT (5000+) unread articles, whatever the value I set it will take a very long time, will try to load all articles and end up freezing. I'll try to restart Chrome too.
The mark as read on scroll fix works great, so most of my others wishes aren't needed, but I liked your idea of adding a gap the size of the hidden article to the beginning to prevent articles from scrolling up when hiding them. I think it would be very useful on each load, when the list is sorting, which may unintentionally mark multiple articles as read… Since for now I can't use the batch size I'll have a lot of loads as I'm scrolling, which increases the risk. Thanks a lot you do a great job !

**Comment by soufianesakhi** [comment]
For the batch size, did you try a small value ? like 40 (in this case it will take a lot of time to load all)
I have tested with 1000+ unread articles, but not with 5000

**Comment by GokuderaElPsyCongroo** [comment]
Yes I even tried with 1 but same effect… I have the "colorful list view" and "faster feedly" extensions enabled too, maybe it can have something to do with that ?
While I'm thinking about it, maybe it should be possible to change the settings without having to load feedly ? Since it's freezing when loading all articles at one, changing the settings afterwards is difficult.

**Comment by soufianesakhi** [comment]
I think 5000 will not be possible I just tested it, It requires a lot of RAM.
Maybe I will implement some load freezing and paging (browse first 600 articles, read them then mark them as read, than load the next 600 etc)

**Comment by GokuderaElPsyCongroo** [comment]
Yes I didn't understand, I though it was already what was doing the batch size. Thank you, that feature would be great. For now I can manually do it by disabling the auto loading while a portion of the articles is loaded and refresh the page, the ability of changing the settings even outside of feedly would help in that case to. Thanks !

**Comment by GokuderaElPsyCongroo** [comment]
Hello, I also noticed that the "kept unread" option in advanced controls doesn't work for me, articles still show up as read while I need to undo an accidental mark all as read. I don't know why feedly didn't implement that feature themselves in the first place… Thank you for your help

**Comment by soufianesakhi** [comment]
Can you give me your exact configuration ? the kept unread works for me

**Comment by GokuderaElPsyCongroo** [comment]
I am on windows 10, last version of Chrome, "colorful list view", "faster feedly" and "feedly notifier" extensions are enabled, could you specify which information you need ?

**Comment by soufianesakhi** [comment]
I meant your settings. You can copy them the console log (and remove the keywords if you have any)

**Comment by GokuderaElPsyCongroo** [comment]
Here there are :
Loaded saved subscription: {"additionalSortingTypes":["4"],"advancedControlsReceivedPeriod":{"hide":false,"keepUnread":false,"markAsReadVisible":false,"maxHours":10,"minPopularity":100,"showIfHot":false},"alwaysUseDefaultMatchingAreas":true,"filteringEnabled":false,"filteringListsByType":{"0":[],"1":[]},"hideAfterRead":false,"hideWhenMarkAboveBelow":true,"keywordMatchingAreas":[0],"keywordMatchingMethod":0,"markAsReadAboveBelow":true,"openAndMarkAsRead":true,"pinHotToTop":false,"restrictingEnabled":false,"sortingEnabled":true,"sortingType":"0","url":"---global settings---"}


And I have a strange error message after :
Uncaught (in promise) TypeError: Cannot read property 'askVisual' of null
    at b.c.Entry.b._askUpdateVisual (web-main-bundle.js:49)
c.Entry.b._askUpdateVisual @ web-main-bundle.js:49

**Comment by soufianesakhi** [comment]
I see that keepUnread in advanced controls is disabled, so it's normal that the articles are marked as read (unless there is a bug and the UI)

**Comment by GokuderaElPsyCongroo** [comment]
No I disabled it when I saw it doesn't work for me…

**Comment by soufianesakhi** [comment]
When it was enabled, was it the only enabled in advanced mark as read ? just to recreate the same settings

**Comment by GokuderaElPsyCongroo** [comment]
Yes

**Comment by soufianesakhi** [comment]
For me it works with only the `Kept unread` checked.
Can you enter in the console the line `getFFnS(ext.lastReadEntryId)` and see if a non null value is displayed ? If ti's null that all the articles are new (publish date less than 10h in your case)

I have noticed a lot of errors generated by feedly in my console too (it's because I use their internal code, so sometimes there are weird side effects generated from function calls I make). These are not impacting, but I plan to fix them in the future

**Comment by GokuderaElPsyCongroo** [comment]
Yes it displays null. Strange… Maybe it uses the date of reception instead of publish date ?

**Comment by soufianesakhi** [comment]
I see the issue. I use the real publish date in my code, but it's the received date that is displayed in feedly next to each article (9h, 1d ...)

**Comment by GokuderaElPsyCongroo** [comment]
Now the commands displays something like 7Wf/KtnFKVZuej/qr9ZnMasSvGPeLmc0GnGGy1SgB2k=_15a3ea49281:ce37f9d:93371e27

**Comment by soufianesakhi** [comment]
ok. I will add in the future the possibility to choose between publish and received date in the calculation / sorting

**Comment by GokuderaElPsyCongroo** [comment]
Thank you. I think that script tries to do something close by "replacing the original relative date with absolute published/received date on Feedly" (even though considering what we just saw, feedly already displays the received date…) : https://greasyfork.org/fr/scripts/1143-feedly-lastmodified-tweak/code
But it doesn't work at all for the issue.
Thank you !

**Comment by soufianesakhi** [comment]
Yes I can do it very easily (there is a crawled timestamp that corresponds to the received date). I will fix it in the next release.
Thanks for discovering the issue :)

**Comment by feedlyTeam** [comment]
Hi there, I've seen it in mentions, so I'll reply to GokuderaElPsyCongroo:  undo an accidental mark all as read - we have this in feedly actually.

**Comment by GokuderaElPsyCongroo** [comment]
Yes but not exactly in the way I need it : I have to enable the option to ask for confirmation before marking as read so I can undo it at the moment I accidentally mark all as read. But in my case I didn't enable that option… What I'm asking to soufianesakhi is the ability to do it at any time, and I understand that even if he implements it, it will still be in some way incomplete, since I'll have to mark as unread a whole batch of articles based on their date, independent of whether or not I already read them (since sorting by popularity tends to make me read first older articles, but that's okay, I haven't been using the sorting option very long).
The best could be having some kind of a "mark all as read history"so we can go back to a previous state, or a way to save the current subscriptions state, but I don't think it's that useful since I don't think somebody would use it all the time.

Sorry again for my weird English, I am French…

**Comment by soufianesakhi** [comment]
Can you test v2.6.3 regarding the performances of loading unread articles ?
I tested with 6000+ unread articles. To auto load all:
- Goggle chrome took less than 1 min 30s, required 800 MB of RAM
- Firefox took less than 3 min, requires much less RAM

**Comment by GokuderaElPsyCongroo** [comment]
Hello (sorry for the response time), I can't try the performances of loading unread articles because the "kept unread" option still doesn't work for me… Then I don't have my 5000+ articles anymore. Sorting by received date works but not that option. I tried the "should be hidden" option to see if it's really an issue with the date… and strangely it works. I didn't try with the "marked as read if visible" because I wasn't sure if I could undo it. Don't know what's going on…

**Comment by soufianesakhi** [comment]
I see, there is a bug is with the kept unread when all the articles should be kept unread.
I'll fix it

**Comment by GokuderaElPsyCongroo** [comment]
It's not all the articles since I "read" way more than 5000 articles in feedly… Also, I tried to keep unread articles from one hour ago to thirty days, it doesn't work for me. Maybe find a way to multiselect articles to keep them unread ? Or create an inverted mark as read on scroll which would unread articles instead ? Probably time consuming, I'm very sorry…

**Comment by soufianesakhi** [comment]
Ok (there is still the bug that I mentioned I will fix it anyway).
Do you see anything in the logs when you try to keep unread articles (a stack trace maybe ?)

**Comment by GokuderaElPsyCongroo** [comment]
No, nothing…

DevTools failed to parse SourceMap: https://feedly.com/i/jquery.min.map
feedly-filtering-and-sorting.js:556 Subscription saved: {"filteringEnabled":false,"restrictingEnabled":false,"sortingEnabled":true,"openAndMarkAsRead":true,"markAsReadAboveBelow":true,"hideWhenMarkAboveBelow":true,"hideAfterRead":false,"sortingType":"0","advancedControlsReceivedPeriod":{"maxHours":730,"keepUnread":true,"hide":false,"showIfHot":false,"minPopularity":100,"markAsReadVisible":false},"pinHotToTop":false,"additionalSortingTypes":["4"],"filteringListsByType":{"0":[],"1":[]},"keywordMatchingAreas":[0],"alwaysUseDefaultMatchingAreas":true,"keywordMatchingMethod":0,"url":"---global settings---"}

**Comment by GokuderaElPsyCongroo** [comment]
Newer than the set date, yes ?

**Comment by soufianesakhi** [comment]
yes. 
what happens when you click the mark as read button, all the articles are marked as read then you undo ? 
I see in your settings that you have setted the date to 30 days and 10 hours.
Do you have articles that are older than that ?

**Comment by GokuderaElPsyCongroo** [comment]
Yes, in subscriptions I can have articles that are months old. By the way is feedly supposed to keep articles that long ?
All articles are (were actually) marked as read when I pressed the button, I don't know if I could undo it because as I way saying to feedly's team member  I didn't enabled the option. But the keep unread option in single articles works

**Comment by soufianesakhi** [comment]
If all articles are marked as read and you don't have articles that are older than the configured than the current date in nyour settings (30 days and 10 hours), the fix that I'm writing will fix the issue.
I will publish it in less than 30 minutes

**Comment by GokuderaElPsyCongroo** [comment]
Thank you very much, you really do a hard work, sorry to bother like that with my issues !

**Comment by soufianesakhi** [comment]
No problem. The v2.6.4 is published

**Comment by GokuderaElPsyCongroo** [comment]
Sorry it still doesn't work, even on another pc it doesn't… Maybe it has something to do with my account ? I'll try to navigate through my settings

**Comment by GokuderaElPsyCongroo** [comment]
Edit: Even with creating another account it doesn't work ! I want to be sure to understand what that feature does : in my case I set it to 30 days, so all articles newer than 30 days are supposed to be unread, right ? That's so weird…

**Comment by soufianesakhi** [comment]
Can you try the script version ? https://github.com/soufianesakhi/feedly-filtering-and-sorting/blob/master/README.md#install-as-a-user-script

(If `Kept unread` is not working then `Marked as read if visible` will work because all the articles are marked as read anyway)

**Comment by GokuderaElPsyCongroo** [comment]
I tried that version with tampermonkey but still doesn't work… I'm a normal user but logged in with google, what surprises me is that it doesn't work even on another pc and account… Are you sure it works for you ? When I choose _hidden_ it works but nothing appends when I choose another option, could it be a graphic problem ? That articles are actually marked as unread or read but they aren't grayed or blacked ? However the article count doesn't change so…
No, _marked as read if visible_ never works for me

**Comment by soufianesakhi** [comment]
So the keep unread does work for you ? It's the marked as read if visible that doesn't work ?
The `marked as read if visible` is an option that is enabled only when `Visible if hot or popularity superior to` is enabled.

**Comment by GokuderaElPsyCongroo** [comment]
Neither the _keep unread_ nor the _visible_ and the _marked as read if visible_ option works, only _hidden_ does

**Comment by soufianesakhi** [comment]
That's not logical.
keep unread not working => all articles are marked as read => visible article are marked as read

**Comment by GokuderaElPsyCongroo** [comment]
Yes I don't understand either : absolutely nothing happens when I set those options

**Comment by soufianesakhi** [comment]
what do you mean by "absolutely nothing happens" ?

**Comment by GokuderaElPsyCongroo** [comment]
For example I have a subscription which contains read and unread articles. I set a date in the advanced controls and select _hidden_ : since it works it will hide all articles newer than the choosed date. But when I select _kept unread_ or any other options, articles stay the same, read articles stay marked as read, unread articles can be marked as read

**Comment by soufianesakhi** [comment]
I see now. So the unread is not checked here ? 
![Feedly settings](https://raw.githubusercontent.com/soufianesakhi/feedly-filtering-and-sorting/master/screenshots/feedly_settings.PNG)

Sorry the script only work when checked.

**Comment by GokuderaElPsyCongroo** [comment]
No I know, I tested with the two options, it doesn't work

**Comment by soufianesakhi** [comment]
I implemented the gap feature in v2.6.5.
I also added some logs regarding the mark as read, you can start a new issue and give me the logs generated by my extension to analyse

**Comment by soufianesakhi** [comment]
Were the articles you wanted to keep unread already read ? (by marking as read on scroll for example)
If this is a case, it's not supported (I will add the option to do it if you confirm)
