### ISSUE TITLE
Problems with Autoload, grouping, incomplete list and other (Safari 15, Big Sur)

### ISSUE THREAD

**Issue by bnSonic** [soufianesakhi/feedly-filtering-and-sorting#124]
Since Months i see these troubles and now i like to take the time to describe them:

SYSTEM
----------
Safari 15.3 (macOS Big Sur)
Feedly filtering and sorting  V3.21.12
Tampermonkey V4.13.6140

SETTINGS
-------------
FFAS Settings:
Auto load all unread articles YES
Load articles by batch - i tried YES and NO, no difference
Sorting enabled YES - Sort by title (a -> z)
Hide duplicates YES - Hightlight YES - FFF6BC (a yellowish color)

Feedly Settings (from the "..." drop down menu):
"Latest"
"Unread only"
  
THE RSS FEED:
-----------------
It seems i cannot see the feed-url in feedly, right? It's this forum-feed:
https://www.mactechnews.de/forum/

PROBLEM
----------
a) It seems that auto-load is not working. If there are many unread items in the feed, i only see the first few of them. When i scroll the list, more and more Items became "yellow" (so duplicates are loaded while scrolling) and new Items appear in the List …

b) But the sorting by title doesn't work either in that case (when items are loading while scrolling). So the alphabetical order isn't there but new loaded items are sorted at the end of the existing list

c) In some cases only a rather small list (a lot of items marked with the duplicate color) are shown. Not enough to scroll the list! In that case, i have no chance to see all unread items (auto load not working and scrolling not available as the list is too small) and i cannot mark them all as read because the buttons at the bottom are missing

c2) if i click on an item (it then expands to see an excerpt) I can scroll down to load more items and see the mark all buttons

d) Often when i click an item, the excerpt doesn't open where i clicked but somewhere else in the list ... a different position. It's the correct item but the position in the list seems to be moved (sorting not working? or getting resorted when a group is clicked?

e) It happens that the whole list (everything!) is vanished if i click an item - a clean page :D … nice but not helpful ;) 

… i could go on but i think that may be enough to see a general problem, right?

As i cannot find other (active) issues with any of that, i came to believe that something is wrong with my system / installation  or with that Safari Version or something?

Any idea what's going wrong - and better: how to fix it? :)
Thanks a lot.

**Comment by soufianesakhi** [comment]
Hello, can you test with Google Chrome and Tampermonkey ?

**Comment by bnSonic** [comment]
With Tampermonkey, no, i think.
I have the filtering and sorting extension for Chrome installed and it works as expected (alle entries are loaded automatically, sorted by title from a to z and duplicates are hidden with a colored background of such entries)
In chrome when i click an entry, this entry is then expanded in the correct place as expected.

On Safari with Tampermonkey it's "a mess" :) … Today the entries were loaded when i scrolled down by myself… but then not everything is sorted correctly (it can't, because that manual fetching of more items). And if i click an entry, today i just get a blank website. 
On Safary with Tampermonkey, for me it's currently broken to point where it's unusable. 

To be clear - i'm not bitter or angry, just sad :) it's a free utility with code available… and it works on Chrome… so i think there is something problematic with Safari or with Tampermonkey or a combination of them.

BTW: Meanwhile i'm on macOS 11.6.5 with Safari 15.4 (16613.1.17.1.13) - if it's a Safari problem, it's not fixed ;)

**Comment by soufianesakhi** [comment]
Thanks for your response, I can't test on Safari on macOS, this extension is only 100% supported on Google Chrome and Firefox
