### ISSUE TITLE
[Wish] Sort Sources on Sidebar

### ISSUE THREAD

**Issue by Ack0** [soufianesakhi/feedly-filtering-and-sorting#13]
Hi!

What do you think about sorting feeds source on sidebar?
Would be cool to sort by name, by number of unread articles, or manually.

**Comment by soufianesakhi** [comment]
Thanks for the suggestions.
I will think about it.

**Comment by soufianesakhi** [comment]
After much consideration, I think there will not be a real added value by implementing this feature as usually the sorting of sources with the unread articles remains approximately the same day to day. I think this can be manually achieved by dragging the sources on sidebar and sorting them accordingly.
Thanks.
