### ISSUE TITLE
Mark multiple articles as unread

### ISSUE THREAD

**Issue by GokuderaElPsyCongroo** [soufianesakhi/feedly-filtering-and-sorting#14]
Hello, thank you very much for adding those features, feedly couldn't be more optimised I think. Sorry to have taken so much of your time with my requests. Don't you think it would be easier if you use the _buttons to mark above/below as read_ as a way to also mark above/below articles as _unread_ ?

**Comment by soufianesakhi** [comment]
added in v2.7.0
