### ISSUE TITLE
[Request] Highlight all the restricted keywords

### ISSUE THREAD

**Issue by anhchuong95** [soufianesakhi/feedly-filtering-and-sorting#18]
I've just found this extension and just love it! Thanks for making this great extension.
As the above title, I think highlighting all the restricted keywords would be a great option. If possible, it is perfect if it can highlight titles with different colors for each defined keyword.

**Comment by soufianesakhi** [comment]
Thanks for the suggestion, I will think of a more general way to color titles based on keywords

**Comment by soufianesakhi** [comment]
Added in v2.8.0 (UI controls => Coloring rules to highlight titles)
