### ISSUE TITLE
Loading next batch without overriding previous articles

### ISSUE THREAD

**Issue by GokuderaElPsyCongroo** [soufianesakhi/feedly-filtering-and-sorting#21]
Hello, thank you very much for adding the batch feature, Feedly is MUCH faster now! I don't know if this is because I moved from Chrome to Firefox but that's great work thank you!!
However, when loading the next batch of articles, all (read) articles above disappear and are literally replaced with the new articles. In other words we have to go back to top to read those new articles, but doing so mark them as read when using the mark as read on scroll. Maybe there should be a feature that triggers a page scroll to top on click to the "load next batch" button, or a way to display articles BELOW that button, so they won't be marked as read. Thanks again!

**Comment by soufianesakhi** [comment]
Hello, thank ou for your feedback.
I can definitely make the page scroll to top on click to the "load next batch" button
