### ISSUE TITLE
A way of sorting articles by title AND received date ?

### ISSUE THREAD

**Issue by GokuderaElPsyCongroo** [soufianesakhi/feedly-filtering-and-sorting#22]
Hello,

Sorting by title is already possible, but is it possible to ensure that it doesn't sort alphabetically, but by picking all stories by the received date (from newest to oldest) ? That would be great if we could read articles by received date, but source by source; I can approximately achieve something by using the additional source levels but it isn't much precise since it only sort entries that have equal sorting.

Thanks for your work!

**Comment by soufianesakhi** [comment]
Hello, can you try this:
- main sorting: Sort by source title (a -> z)
- additional sorting: Sort by received date (newest first)
Thanks

**Comment by GokuderaElPsyCongroo** [comment]
Thanks for your answer,

When I try that, all sources are sorted alphabetically, and only their articles are sorted by received date. I would prefer something of the opposite : sorting all the batch by received date, independently of the source, then grouping that sorted batch by feed, starting with the current newest, so I will be able to read all the new articles of one feed at once, not alphabetically but by their date of receipt.

Sorry, I don't know if I'm clear, I am French

**Comment by soufianesakhi** [comment]
So if I understood correctly, you want a sorting by source starting with the one containing the newest article?

**Comment by GokuderaElPsyCongroo** [comment]
Yes that would be great (and of course all sources included in the batch would be sorted the same way according to their date)

**Comment by soufianesakhi** [comment]
Added in v3.1.0: Sort by source title (newest received first)
