### ISSUE TITLE
Support keep as unread when marking as read via script buttons

### ISSUE THREAD

**Issue by GokuderaElPsyCongroo** [soufianesakhi/feedly-filtering-and-sorting#23]
Hello,

Keeping unread (via feedly, not using your script) and scrolling using the "mark as read on scroll" works, but not if I use the "mark above/below as read" and "the mark as read and go to the next batch" buttons : it will override it and mark as read.

Also, it probably has to do with the recent feedly update, the button to open articles in a new tab have been replaced by a blank space.

Thank you

**Comment by soufianesakhi** [comment]
Hello,

For the first 2 points, I am aware of these issues, it will need a lot of time to support the keep as unread for these cases (not trivial).

For the last point, are you talking about this icon: http://findicons.com/files/icons/2315/default_icon/256/open_in_new_window.png ?
If so can you do a hard refresh or clear cache and refresh ?

Thanks

**Comment by GokuderaElPsyCongroo** [comment]
Sorry is it takes a lot of time, personally I don't use those features much…

Yes that's the icon, unfortunately clearing the cache didn't work (but the button still works so it isn't bothering, please don't take too much time for this, your script is great already)

Thanks !

**Comment by soufianesakhi** [comment]
even CTRL + F5 on the feedly page didn't do anything? If you able to open the link and see the image it should normally appear. Can you open the network panel of the browser's console and check if open_in_new_window.png is loaded (with Status=200)?

**Comment by GokuderaElPsyCongroo** [comment]
It doesn't has any status but feedly tries to use https instead of http, maybe the problem has to do with Firefox instead of Feedly ? Let me try another browser to see

**Comment by soufianesakhi** [comment]
Maybe you have an extension that tries to redirect to https. Maybe add an exception if it's the case for findicons.com.

**Comment by GokuderaElPsyCongroo** [comment]
You're right ! I had the addon "Mixed Content Hunter", I disabled it and it works now. Thank you!
