### ISSUE TITLE
sync all your setting using google chrome built-in sync mechanism?

### ISSUE THREAD

**Issue by lingliugithub** [soufianesakhi/feedly-filtering-and-sorting#29]
Hi developer, 

Thanks so much for developing this useful plugin.

It is possible to have a better sync mechanism by sync all the setting (e.g., filtering keywords, UI color, keywords, etc,) using the built-in sync of chrome? Keeping a consistent setting on my several computers for your plugin might be not so easy because I have to export and import every time and have to distinguish which one is the most-updated.
Just like "Check plus for gmail", it syncs all its setting via the chrome. 
Thanks!
Regards,
Ling

**Comment by soufianesakhi** [comment]
Available in v3.6.0

**Comment by lingliugithub** [comment]
Hi,

The sync function works perfectly! Thanks!!
