### ISSUE TITLE
Bug: Two new sorting levels are added after clicking some source in sidebar

### ISSUE THREAD

**Issue by Ack0** [soufianesakhi/feedly-filtering-and-sorting#3]
When Feedly is loaded  for the first time, everything is fine:
http://i.imgur.com/9a4OT6i.jpg

But if I click on some source in left sidebar, two new sorting levels are added:
http://i.imgur.com/9B0TU5Y.jpg

And this happen every time I click:
http://i.imgur.com/Xckn4Ml.jpg

**Comment by soufianesakhi** [comment]
Fixed in 1.5.4.2 :)
