### ISSUE TITLE
Open new tabs in background

### ISSUE THREAD

**Issue by Keith94** [soufianesakhi/feedly-filtering-and-sorting#31]
The custom button for "open articles in a new tab and mark them as read" always opens new tabs in the foreground. Please add the ability to open them in the background instead.

**Comment by soufianesakhi** [comment]
Hello, this can't be controlled by the extension sadly. It can only configured in your browser.

Example for Firefox: browser.tabs.loadBookmarksInBackground should be set to true in about:config

I don't know if it's possible inChrome (maybe with the help of an extension ?)

**Comment by Keith94** [comment]
I have `browser.tabs.loadInBackground` set to true (browser default) and the bookmarks one too. But the Feedly articles are always opening in the foreground regardless of that setting.

![image](https://user-images.githubusercontent.com/5490615/31300687-d9fd6288-aaa9-11e7-9a2f-ec454e15f084.png)

**Comment by soufianesakhi** [comment]
switch browser.tabs.loadDivertedInBackground to true also

**Comment by Keith94** [comment]
That did the trick. Unfortunately that also affects links opened from other applications (Sublime Text, etc.)...

Is there another way to implement it, like clicking on the article's title will open in a new tab instead?

**Comment by soufianesakhi** [comment]
There will still be the same problem because this behavior can't be controlled by Javascript, it's browser defined. Sorry

**Comment by GokuderaElPsyCongroo** [comment]
You could use the middle mouse button ? (by clicking on the title, not the custom button) I always do that and it works fine (it won't mark as read but it shouldn't be a problem).
