### ISSUE TITLE
Allow to chose to mark as read or not when opening in a new tab

### ISSUE THREAD

**Issue by GokuderaElPsyCongroo** [soufianesakhi/feedly-filtering-and-sorting#33]
Hello,

I think that feature would fix the sorting problem : I tried for a while to open articles without marking them as read (using the middle mouse button), and I could browse all articles of the batch without seeing it sort itself. That way I would read all articles of the batch without marking them as read, and simply use the "mark all the batch as read and load next batch" button without issues.
I'll close my previous issue then, since I think it would fix it.

Thank you,

**Comment by soufianesakhi** [comment]
Hello, thanks for the requests, but I don't have a lot of free time these days. I would work on them as soon as possible
