### ISSUE TITLE
Most popular and "you may also like" not loading when loading next batch

### ISSUE THREAD

**Issue by GokuderaElPsyCongroo** [soufianesakhi/feedly-filtering-and-sorting#34]
Hello,

Most popular section and the "You may also like" in magazine view will only load again when manually refreshing the page. A way to make them load when marking the batch as read ?

Thanks,

**Comment by soufianesakhi** [comment]
This will not be possible because these suggestions and the popular section is loaded only once by Feedly per subscription.
