### ISSUE TITLE
Sorting before batch load

### ISSUE THREAD

**Issue by GokuderaElPsyCongroo** [soufianesakhi/feedly-filtering-and-sorting#37]
Hello,

I don't know if it's possible, but I currently feel like the loading by batch feature picks articles by received date, so if I choose to load a batch of 100, it will give me the 100 newest articles.

The problem I think, is that this is done independently of the sorting options. I use the randomizer a lot (that was a request from me and I thank you a lot, no rss reader can provide such a feature, and without the rather slow Feedly team, you are greatly improving the service :B); so I use the randomizer, and I would like to be able to load articles by batch (so I don't encounter lags), but a batch composed of 100 random articles.

Which means the sorting would be processed before displaying the batch (with the benefit that I'd be able to refresh that same batch at the end of the list, to potentially include new articles on that new load).

If it's possible thank you very much. I know I do a lot of requests, please don't try if it's too annoying
(and again I hope I am comprehensible; sorry for my English, I am French)

**Comment by soufianesakhi** [comment]
Merci pour tes contributations !
Oui effectivement cela ne sera pas possible car l'API interne de Feedly qui permet de charger les articles ne le permet pas.

**Comment by soufianesakhi** [comment]
Merci pour tes contributions !
Oui effectivement cela ne sera pas possible car l'API interne de Feedly qui permet de charger les articles ne le permet pas.

**Comment by GokuderaElPsyCongroo** [comment]
Non merci à toi, tu fais un boulot formidable ! C'est vraiment dommage que l'équipe de Feedly n'assume pas ce genre d'améliorations par elle-même et soit trop occupée à nous sortir des "boards", intéressants mais pas franchement prioritaires par rapport à la possibilité de filtrer les articles en double ou même d'ouvrir les articles dans un nouvel onglet ! J'ai la triste impression qu'ils ne sont pas vraiment à l'écoute des demandes pourtant populaires que la communauté leur fait, alors heureusement que tu es là, merci beaucoup.

Bon courage, et ne consacre pas trop de ton temps à nos demandes ; le lecteur est déjà quasiment parfait grâce à toi :)
