### ISSUE TITLE
Fixes for OUJS

### ISSUE THREAD

**Issue by Martii** [soufianesakhi/feedly-filtering-and-sorting#39]
Greetings,

OUJS has made a change recently to require SPDX codes for OSI approved licensing.

In order to improve the appearance of your script homepages it would be appreciated if you could modify all of your affected scripts

Currently this will be a blocker:

``` js
 // @license     MIT licensed, Copyright (c) 2016-2017 Soufiane Sakhi (https://opensource.org/licenses/MIT)
```

... please use this instead...

``` js
 // @copyright   2016-2017, Soufiane Sakhi
 // @license     MIT; https://opensource.org/licenses/MIT
```

I would do a pull request but it would appear at a quick skim that you make the .user.js dynamically or have several places that would need the change besides [here](https://github.com/soufianesakhi/feedly-filtering-and-sorting/blob/master/script/Feedly_filtering_and_sorting.user.js).

Until this change is made you will be unable to update those affected scripts.

Thanks,
OUJS Staff

**Comment by soufianesakhi** [comment]
Hello,
this was fixed in the latest version.
Thanks
