### ISSUE TITLE
Script does not work after the last Feedly update

### ISSUE THREAD

**Issue by Ack0** [soufianesakhi/feedly-filtering-and-sorting#4]
Hi!
Feedly changed the UI and now the script does not work. :(
Do you plan fix it?
Thanks in advance.

Edit:
As workaround I checked "Old Miro-based rendering engine (deprecated)" inside Preferences > General and the script is working again. :)

**Comment by soufianesakhi** [comment]
Try the v2.0.0 version

**Comment by soufianesakhi** [comment]
Feedly are trying different things these days, so I expect this version to not be stable

**Comment by soufianesakhi** [comment]
The old version of the script can be found here:
https://github.com/soufianesakhi/feedly-filtering-and-sorting/raw/v1/script/Feedly_filtering_and_sorting.user.js

**Comment by Ack0** [comment]
Thanks a lot for the old version. I will stay with it until I have time to change my small .css userstyle.

Just to let you know, I tested the new version for 2 hours at least and everything seems to be fine.

**Comment by soufianesakhi** [comment]
The 2.0.1 version of the script is fully compatible now with the new design.
