### ISSUE TITLE
Group to top highlighted articles

### ISSUE THREAD

**Issue by GokuderaElPsyCongroo** [soufianesakhi/feedly-filtering-and-sorting#40]
Hello,

That could be an interesting feature trying to mimic the [scoring system](https://git.tt-rss.org/git/tt-rss/wiki/Scoring) of tt-rss, for a more efficient sorting.

Thanks a lot,

**Comment by soufianesakhi** [comment]
This scoring system is quite complex to implement. I would consider it if more users are interested.
