### ISSUE TITLE
Order of buttons for marking articles read above/below are reversed for un-expanded list item

### ISSUE THREAD

**Issue by mangino** [soufianesakhi/feedly-filtering-and-sorting#41]
See image below:

![markarticlesreadbuttonsreversed](https://user-images.githubusercontent.com/5480528/32960321-804aab56-cb92-11e7-94ce-7d1e7a3b2d85.png)

**Comment by soufianesakhi** [comment]
Hello, sorry these buttons were not designed for the expanded article case.

**Comment by mangino** [comment]
Thanks for the reply. But I'm confused. Does this mean you will be removing them? They are very useful in the expanded article. (That's the only place I do use them.) I think you should leave them there and change their order to match how they look in the unexpanded case. Thanks.
