### ISSUE TITLE
Sort by day, then by popularity

### ISSUE THREAD

**Issue by Ack0** [soufianesakhi/feedly-filtering-and-sorting#42]
Hi!

I'm trying to sort by day, then by popularity, but when sorting by date the hour is taken into account. I would like to sort only by day, not by hours.

This is what is happening:
Article 1 | published 2017.12.**18**, 06:00 | popularity **100**
Article 2 | published 2017.12.**18**, 07:00 | popularity **200**
Article 3 | published 2017.12.**18**, 08:00 | popularity **300**
Article 4 | published 2017.12.**19**, 06:00 | popularity **100**
Article 5 | published 2017.12.**19**, 07:00 | popularity **200**
Article 6 | published 2017.12.**19**, 08:00 | popularity **300**

This is what I would like to achieve:
Article 3 | published 2017.12.**18**, 08:00 | popularity **300**
Article 2 | published 2017.12.**18**, 07:00 | popularity **200**
Article 1 | published 2017.12.**18**, 06:00 | popularity **100**
Article 6 | published 2017.12.**19**, 08:00 | popularity **300**
Article 5 | published 2017.12.**19**, 07:00 | popularity **200**
Article 4 | published 2017.12.**19**, 06:00 | popularity **100**

Thanks in advance!

**Comment by Ack0** [comment]
Hi,

I think I found a bug, but I don't know exactly how to reproduce it.

My setup is

Auto load all unread articles
Sort by source title (a-z)
Sort by publish day (new first)
Sort by popularity (highest to lowest)
Sort by title (a-z)

but after load all articles, I got this:

https://i.imgur.com/Vn3Lyqt.png

The popularity is not being obeyed.
Can you look this?
If I find out how to reproduce it, I'll come back here.

Thank you!

**Comment by soufianesakhi** [comment]
Hello,
It's normal because you sort by publish day before popularity

**Comment by soufianesakhi** [comment]
Yes It's the actual day (just see you examples at the top).
9:38 AM and 10h ago are different days exactly.

**Comment by Ack0** [comment]
Ok. Now I get it.
I did think that all articles that are 'XXh' should obey the hour.
Thank you for clarify this. 👍
