### ISSUE TITLE
100% CPU

### ISSUE THREAD

**Issue by safronov3d** [soufianesakhi/feedly-filtering-and-sorting#48]

**Comment by safronov3d** [comment]
mac, chrome 67, ad block disabled, standard settings, several words in filter.

![Alt text](https://i.gyazo.com/8c2ffe19a0a022f69bb0aa593f8791a6.png)

**Comment by soufianesakhi** [comment]
Do you use the extension version or the script version ?
The CPU is normal when disabling my extension/script ?

**Comment by safronov3d** [comment]
Extension from chrome web store, disabled = 0,1 % CPU

**Comment by soufianesakhi** [comment]
Can you open the console log and see if there are any errors for the scripts: 
"feedly-filtering-and-sorting.js"
"Feedly-Page-FFnS.js"
starting with "window-"
starting with  "classes-*"

**Comment by soufianesakhi** [comment]
Can you try the script version with Tampermonkey.
1- Export the settings
2- Disable the extension
3- Install https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=en
4- Install https://greasyfork.org/en/scripts/20483-feedly-filtering-and-sorting
5- Open feedly and import the settings

Then check if there is still the same CPU problem

**Comment by safronov3d** [comment]
Everything works fine through a tampermonkey script CPU 0,1%

Extension CPU 100%:

> [feedly] Loading pages...
> jquery.min.js:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
> send @ jquery.min.js:4
> ajax @ jquery.min.js:4
> WebExtInitializer.loadScript @ feedly-filtering-and-sorting.js:382
> initResources @ feedly-filtering-and-sorting.js:3498
> (anonymous) @ feedly-filtering-and-sorting.js:3514
> j @ jquery.min.js:2
> k @ jquery.min.js:2
> setTimeout (async)
> (anonymous) @ jquery.min.js:2
> i @ jquery.min.js:2
> fireWith @ jquery.min.js:2
> fire @ jquery.min.js:2
> i @ jquery.min.js:2
> fireWith @ jquery.min.js:2
> ready @ jquery.min.js:2
> setTimeout (async)
> (anonymous) @ jquery.min.js:3
> (anonymous) @ jquery.min.js:2
> (anonymous) @ jquery.min.js:2
> index.17352632bb3c8148f574.js:1 [feedly][fastLoad] data already ready
> index.17352632bb3c8148f574.js:1 [feedly][feedly] available:   subscriptions=65, userId=1461ceb8-738a-4d95-8e47-c3854f174e38, plan=standard, wave=2014.29, product=undefined, unreadCounts=78
> index.17352632bb3c8148f574.js:1 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
> c.addEventListener @ index.17352632bb3c8148f574.js:1
> t.bind @ index.17352632bb3c8148f574.js:1
> t.load @ index.17352632bb3c8148f574.js:1
> d.start @ index.17352632bb3c8148f574.js:1
> (anonymous) @ index.17352632bb3c8148f574.js:1
> e.callbackApply @ index.17352632bb3c8148f574.js:1
> e.callback @ index.17352632bb3c8148f574.js:1
> onComplete @ index.17352632bb3c8148f574.js:1
> (anonymous) @ index.17352632bb3c8148f574.js:1
> e.callbackApply @ index.17352632bb3c8148f574.js:1
> e.callback @ index.17352632bb3c8148f574.js:1
> devhd.io.GET.Content-Type @ index.17352632bb3c8148f574.js:1
> c.onreadystatechange @ index.17352632bb3c8148f574.js:1
> index.17352632bb3c8148f574.js:1 [Violation] 'readystatechange' handler took 156ms
> feedly-filtering-and-sorting.js:3518 Feedly page fully loaded
> feedly-filtering-and-sorting.js:940 Loaded saved subscription: {"additionalSortingTypes":[],"advancedControlsReceivedPeriod":{"hide":false,"keepUnread":false,"markAsReadVisible":false,"maxHours":6,"minPopularity":200,"showIfHot":false},"alwaysUseDefaultMatchingAreas":true,"autoRefreshEnabled":false,"autoRefreshMinutes":60,"coloringRules":[],"filteringByReadingTime":{"enabled":false,"filterLong":true,"keepUnread":false,"thresholdMinutes":5,"wordsPerMinute":200},"filteringEnabled":false,"filteringListsByType":{"0":[],"1":[]},"hideAfterRead":false,"hideDuplicates":false,"hideWhenMarkAboveBelow":false,"keywordMatchingAreas":[0],"keywordMatchingMethod":0,"markAsReadAboveBelow":false,"markAsReadAboveBelowRead":true,"markAsReadDuplicates":false,"markAsReadFiltered":false,"markAsReadOnOpenCurrentFeedArticles":true,"maxOpenCurrentFeedArticles":0,"openAndMarkAsRead":true,"openCurrentFeedArticles":false,"openCurrentFeedArticlesUnreadOnly":true,"pinHotToTop":false,"replaceHiddenWithGap":false,"restrictingEnabled":false,"sortingEnabled":true,"sortingType":0,"titleOpenAndMarkAsRead":false,"url":"---global settings---","visualOpenAndMarkAsRead":false}
> 2feedly-filtering-and-sorting.js:1350 Sorting articles at 22:50:37 GMT+0300 (Moscow Standard Time)
> (index):13 [Violation] Avoid using document.write().
> renderFrameContents @ (index):13
> componentDidMount @ (index):13
> e.notifyAll @ (index):8
> close @ (index):11
> closeAll @ (index):11
> perform @ (index):11
> perform @ (index):11
> perform @ (index):11
> S @ (index):11
> closeAll @ (index):11
> perform @ (index):11
> batchedUpdates @ (index):10
> c @ (index):11
> r @ (index):11
> enqueueSetState @ (index):11
> r.setState @ (index):12
> (anonymous) @ (index):14

**Comment by safronov3d** [comment]
ok, sry chrome 67 for mac bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=848210

**Comment by soufianesakhi** [comment]
No problem :)
