### ISSUE TITLE
Buttons not showing

### ISSUE THREAD

**Issue by Mornon** [soufianesakhi/feedly-filtering-and-sorting#49]
I'm trying to use this extension from Chrome's store and I see the filtering button to access settings, but I tried checking "Add buttons to mark articles above/below as read" and the buttons don't appear (nor does any other button).

I tried disabling all extensions beside this one, to no avail. I'm running Chrome 68.0.3440.106 on Windows 10 1803 17134.228.

Edit: I also tried installing the script with Tampermonkey, same issue.

**Comment by soufianesakhi** [comment]
Hello,
Which view are you using (Title-Only, Magazine, ...) ?
Do you have the same problem when switching to another view ?

**Comment by Mornon** [comment]
Hello,
title only; I tried all possible layout, I can see any more button.

**Comment by Mornon** [comment]
Yes, that works.

![20180818 144116](https://user-images.githubusercontent.com/21358808/44299376-d4295a80-a2f4-11e8-9b73-c70bd7f82cce.png)

**Comment by soufianesakhi** [comment]
Can you enable "buttons to mark articles above/below" (enable the first checkbox), then in the browser console => Elements tab, can you search (ctrl+F) the following:
`.entry .mark-as-read-above-below-button`
Do you have any matches ?

**Comment by Mornon** [comment]
160 like this:

`<button class="mark-as-read-above-below-button mark-below-as-read mark-as-read condensed-toolbar-icon icon" title="Mark articles below as read/unread" type="button" style=""></button>`

**Comment by soufianesakhi** [comment]
Can you send me a screenshot of an article with the mouse hovering it ? (use print screen keyboard button and crop the image to only the article if you want)

**Comment by Mornon** [comment]
... I found the buttons. I was looking for them where the other buttons appears and I totally missed them in the article, sorry.

**Comment by soufianesakhi** [comment]
no problem :)
