### ISSUE TITLE
Auto-Load

### ISSUE THREAD

**Issue by sunhuang** [soufianesakhi/feedly-filtering-and-sorting#51]
Auto-Load doesn't seem to work for me. I only get 40 articles at a time. Batch function also doesn't seem to work. Am I doing something wrong?

**Comment by sunhuang** [comment]
Nevermind I figured it out. The extension doesn't work if I also have Feedly sort my feeds by most popular; had to set it to sort by latest to get it to autoload. Great app!

**Comment by soufianesakhi** [comment]
Hello, It's supposed to auto load even when sorting by popularity.
Do you have a premium feedly account ?
If not:
Which browser are you using ?
Did you test with batch mode disabled ?

**Comment by embql** [comment]
Hi
I get the same issue I believe, but the 'auto-load all articles' doesn't work correctly - the first 50 articles or so are loaded, and when I then scroll down, the next articles load when I'm about to reach the bottom - then when the next articles load, some popular articles are sorted correctly and sent to the top, forcing me to start all over again to hunt for the newly loaded articles sandwiched in between already seen articles (and auto-mark as read makes it hard to find as well :p)

Please ask if you need more information or details, or if I can't explain myself correctly ;) !
