### ISSUE TITLE
Find or Highlight duplicate

### ISSUE THREAD

**Issue by Su333** [soufianesakhi/feedly-filtering-and-sorting#53]
I wish if there is a way to find or highlight duplicated items

**Comment by soufianesakhi** [comment]
Hello,
There is already an option to hide duplicate items, but I can definitely add a highlight option to keep both versions but color the older one.

**Comment by Su333** [comment]
Great, It is definitely awesome to have this option for me. Thank you!!

**Comment by soufianesakhi** [comment]
Available in v3.13.0
