### ISSUE TITLE
Auto Sort by Popularity (Highest to Lowest) for any Category

### ISSUE THREAD

**Issue by User1282** [soufianesakhi/feedly-filtering-and-sorting#54]
Hi there! First of all, thank you for the extension. I was looking for a solution to sort my feeds (entries) according to popularity.
I organize my feeds by category (e.g. Technology, News, etc.) and every time that I want to see my feeds sorted by popularity, I have to press the refresh button on Google Chrome.
Is it possible to receive my feeds, given a category, ordered by popularity (highest to lowest) without having to refresh the browser in every new category?

Thanks!

**Comment by soufianesakhi** [comment]
Thanks for reporting this issue, I will fix it as soon as possible

**Comment by soufianesakhi** [comment]
Can you test the 3.12.4 version ?

**Comment by User1282** [comment]
Working perfectly now! Many thanks!
