### ISSUE TITLE
Do not mark hidden articles as read

### ISSUE THREAD

**Issue by mkomko** [soufianesakhi/feedly-filtering-and-sorting#55]
I just discovered your extension/script. I have been wanting the feature to hide articles "newer than..." to avoid spoilers forever! So awesome, thank you very much.

However, I just noticed that hidden articles are still being marked as read when using the setting "Articles received less than x hours ago should be: Hidden". The setting "Mark as read filtered articles" does not seem to apply to hidden articles.

It would be really great if it was possible to keep hidden articles as unread (for later reading), either by default (if you think that's preferred by everyone) or as a new option or by also applying the setting for filtered articles to hidden articles.

Thank you very much in advance for your feedback!

**Comment by soufianesakhi** [comment]
You should check the `Kept unread if unread` option if you want to keep these recent articles unread

**Comment by mkomko** [comment]
Got it, thanks a lot! Somehow I didn't connect one option to the other, sorry about that.
Thanks!
