### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by saputnik** [soufianesakhi/feedly-filtering-and-sorting#56]
Since this morning, on two different computer, the Feedly page appears completely blank. When I deactivate Feedly filtering and sorting the page starts working again properly. Any idea how to solve the issue?

**Comment by saputnik** [comment]
If it is of any help, when Feedly starts I see shortly the auto loading all articles message and then the page goes blank

**Comment by soufianesakhi** [comment]
Thanks for reporting the issue. I'm looking into it.

**Comment by saputnik** [comment]
Thank you so much! And also thanks for the extension, it's great

**Comment by nionis** [comment]
^ I second that

**Comment by soufianesakhi** [comment]
It should be fixed in v3.13.2

**Comment by saputnik** [comment]
> It should be fixed in v3.13.2

Great, thanks! Is it already available for downloading?

**Comment by soufianesakhi** [comment]
Publishing in progress for Chrome, already published for other plaftforms

**Comment by saputnik** [comment]
> Publishing in progress for Chrome, already published for other plaftforms

Everything works perfectly as before. Thank you so much for everything!

**Comment by soufianesakhi** [comment]
You're welcome :)
