### ISSUE TITLE
Blank page on item hide action

### ISSUE THREAD

**Issue by tsitelov** [soufianesakhi/feedly-filtering-and-sorting#57]
Each time I read-hide an item using key 'x' or clicking X-symbol, feed part of a page becomes blank. 

Refresh or page reload fixes the issue until a next hide action. 

Google Chrome 72.0.3626.119, macOS 10.13.6,  Feedly PRO, Plugin version: 3.13.3

**Comment by soufianesakhi** [comment]
Can you export your settings, remove any sensitive keyword if you want to, and share it with me ?

**Comment by tsitelov** [comment]
Sure: https://gist.github.com/tsitelov/9b468492b29d594cecf65aeefebbf0a9

**Comment by soufianesakhi** [comment]
Fixed in v3.13.4
