### ISSUE TITLE
Issue with sorting Option

### ISSUE THREAD

**Issue by Eldorhaan** [soufianesakhi/feedly-filtering-and-sorting#58]
Hi Sofiane,

I have an issue with the sorting option by popularity. I choose Highest to lowest.
![image](https://user-images.githubusercontent.com/49403344/55729282-e7756b80-5a26-11e9-9910-249f99247002.png)

But on the feedly view, it stay by latest
![image](https://user-images.githubusercontent.com/49403344/55729517-55ba2e00-5a27-11e9-9966-635bdeae77a1.png)

If I activate the native option "filtered by popularity" It's ok, but I loose the batch option of your script.
![image](https://user-images.githubusercontent.com/49403344/55729704-ab8ed600-5a27-11e9-8a50-abff69820f08.png)

Am I doing something wrong ?

**Comment by Eldorhaan** [comment]
This is my global settings:
![ScreenClip](https://user-images.githubusercontent.com/49403344/55729851-f872ac80-5a27-11e9-91a1-2f93cf86eb65.png)

**Comment by soufianesakhi** [comment]
Hello, nothing is wrong, the entries are well sorted even if the `LATEST` is displayed. Just ignore the text.
I will update/remove this text in a future version.

Keep the `Latest` option checked though instead of `Most Popular` in the Feedly 3 dot settings

**Comment by Eldorhaan** [comment]
So how to have the articles sorted by popularity and displayed by batch of 200 ? Because it doesn't do it for now.

**Comment by soufianesakhi** [comment]
You have to check `Auto load all unread articles` to enable the batch mode

**Comment by Eldorhaan** [comment]
For example, on my "All" category, I have popular articles, like on this screen just maid:
![ScreenClip](https://user-images.githubusercontent.com/49403344/55730661-bf3b3c00-5a29-11e9-8452-639cc3f07198.png)
But if I turn it on the latest option, I loose the sorting by popularity 
![ScreenClip](https://user-images.githubusercontent.com/49403344/55730694-d67a2980-5a29-11e9-9265-0d4def729d36.png)
Here my Options:
![ScreenClip](https://user-images.githubusercontent.com/49403344/55730821-18a36b00-5a2a-11e9-865a-c5fff28d23ac.png)

**Comment by soufianesakhi** [comment]
Did you try to refresh the navigator tab after changing the settings?
It's also possible that the `All` category page displays the top 40 articles when you choose the `Most Popular` feedly sorting, and the most recent articles when choosing `Latest`. Can you confirm? (the `Most Popular` feedly sorting is only available  for pro users)

**Comment by soufianesakhi** [comment]
It's normal because feedly load the 200 most recent articles that aren't forcibly the most popular

**Comment by Eldorhaan** [comment]
I am a pro user. But I think i figure out what is happening. At the beginning of the installation I have load the all articles, without batch option, the I made a reload. After I have done some other manipulation, but I think you script is considering that all the article have been read. Because see the screen, it marks some new article by popularity now, the three first.
![ScreenClip](https://user-images.githubusercontent.com/49403344/55731661-a2076d00-5a2b-11e9-9ab4-5ad33a438138.png)

I think the script doesn't mark "as read" like feedly state. It's just my suggestion :)

**Comment by Eldorhaan** [comment]
See I am just doing a F5 refresh, and articles seems to be incremented after new changed from sources.
![ScreenClip](https://user-images.githubusercontent.com/49403344/55732055-51444400-5a2c-11e9-98d9-a32fe6aedefd.png)

**Comment by soufianesakhi** [comment]
Yes that's what I thought :)
When you enable the batch mode (let's say batch size = 200) with recent being checked, feedly will load only the 200 most recent articles. If you have more then 200 unread articles, some popular articles will not be loaded until you mark the first batch as read.

**Comment by Eldorhaan** [comment]
It seems it's related also by "feed category", if I change for example into Africa, I get much more articles: 
![ScreenClip](https://user-images.githubusercontent.com/49403344/55733103-468aae80-5a2e-11e9-9e42-0d06eb7f40f2.png)

**Comment by soufianesakhi** [comment]
Yes that's because there are fewer articles to load, so the popular articles are loaded with the first batch

**Comment by Eldorhaan** [comment]
Do you think, this is possible to shrink this in future updates ?

**Comment by soufianesakhi** [comment]
Do you want to reduce the number of article loaded per batch ? This is already possible from the extension's `Batch size` setting

**Comment by Eldorhaan** [comment]
No I just want to load more popular and less "latest" to be more specific, to have on 200 articles loaded, 200 articles popular sorted. Like the most popular sorting option but not blocked to 40

**Comment by soufianesakhi** [comment]
This is not possible I'm afraid. You can try to increase the batch size, or try to auto load all articles without using the batch mode
