### ISSUE TITLE
Feedly Update

### ISSUE THREAD

**Issue by Eldorhaan** [soufianesakhi/feedly-filtering-and-sorting#59]
Hello Soufiane,

Today it seems feedly have updated their software, and the app seems not running anymore, can you confirm or maybe it's another thing ?

**Comment by saputnik** [comment]
> Hello Soufiane,
> 
> Today it seems feedly have updated their software, and the app seems not running anymore, can you confirm or maybe it's another thing ?

Same problem here

**Comment by soufianesakhi** [comment]
Thanks for reporting the issue. Maybe they are A/B testing a new version because I still have the old version . As soon as the new version is released, I will try to fix the extension.

**Comment by soufianesakhi** [comment]
I think it's rather a bug in the extension. I will try to fix it.

**Comment by Eldorhaan** [comment]
Thank you very much Soufiane to figure out this so quickly.

**Comment by saputnik** [comment]
> I think it's rather a bug in the extension. I will try to fix it.

Thanks!

**Comment by soufianesakhi** [comment]
It was a Feedly code change that impacted some of the extension's advanced controls and auto loading. It's fixed in v3.13.5. (Don't forget to give a star if you like this extension :) )
