### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by askearitza** [soufianesakhi/feedly-filtering-and-sorting#6]
Thank you for your reply at the Google store. What I most would appreciate right now is an addition to search beyond the title, in the body of an entry. There are keywords inside the text of some feeds that I want to filter (in or out).

More thorough documentation would be nice too. I was confused by how the different general settings and subscription settings work and what they do, even though I am not new to filtering.

Thanks again for sharing this with us!

**Comment by soufianesakhi** [comment]
With the 2.4.1 version you can search specific areas (title, body or author).
Check the keyword controls section.
More documentation will be added soon, in the meantime check the releases page: https://github.com/soufianesakhi/feedly-filtering-and-sorting/releases
