### ISSUE TITLE
Redundancy of article 

### ISSUE THREAD

**Issue by Eldorhaan** [soufianesakhi/feedly-filtering-and-sorting#60]
Hi Soufiane,

I hope i am not bothering you. Just a question, is your extension normally mark as read all double or triple articles ? Cause I see some coming twice.
![image](https://user-images.githubusercontent.com/49403344/55871763-6a6c0280-5b9c-11e9-8449-8ed16847b9c3.png)

**Comment by soufianesakhi** [comment]
That's the RSS feed that publishes the same article multiple times. To get rid of duplicates you can check the `Duplicates filtering` option in the advanced controls section :)
