### ISSUE TITLE
What's the proper node.js version of development environment?

### ISSUE THREAD

**Issue by PeterDaveHello** [soufianesakhi/feedly-filtering-and-sorting#61]
Hi @soufianesakhi,

I'd like to send some pull requests to this awesome, useful project, I see some instructions in DEV_INSTRUCTIONS.md, but the node.js version seems to be missing, may I know what's your development environment? I can also help update in DEV_INSTRUCTIONS.md file, thanks!

**Comment by soufianesakhi** [comment]
Hello @PeterDaveHello,

Thank you for your interest in contributing to this project !
You can use node.js version 10 (LTS) for your development.

Let me know if you need more instructions / infos

**Comment by PeterDaveHello** [comment]
Thanks @soufianesakhi!
Mind me to add that info in the repository?

**Comment by soufianesakhi** [comment]
I will add it along with other infos (code formatting etc.)

**Comment by PeterDaveHello** [comment]
Nice!
