### ISSUE TITLE
Problems with sorting

### ISSUE THREAD

**Issue by saputnik** [soufianesakhi/feedly-filtering-and-sorting#63]
Hey, again me, sorry for bothering... since yesterday I am getting a duplicate icon of Feedly Filtering and Sorting (see screenshot) and sorting currently doesn't work. 

Any idea how to solve the problem?

<img width="757" alt="Screenshot 2019-04-22 at 09 45 34" src="https://user-images.githubusercontent.com/48006970/56489867-84cea600-64e3-11e9-9b7f-65e06e10e00b.png">

**Comment by soufianesakhi** [comment]
Hello,
Regarding the sorting issue, I noticed that the popularity is updated by Feedly after the articles are loaded, the extension only sorts according to the initial popularity.
I will try to find a solution to this issue along with the duplicate icon one.

**Comment by saputnik** [comment]
Thank you so much, kind and helpful as usual :)

**Comment by soufianesakhi** [comment]
Should be fixed in the latest published version
