### ISSUE TITLE
button missing

### ISSUE THREAD

**Issue by Mr-Phone** [soufianesakhi/feedly-filtering-and-sorting#64]
after I click the refresh button
the feedly filtering-and-sorting logo is missing
version 3.13.7
download from chrome store
before
![image](https://user-images.githubusercontent.com/9606042/56587454-25bc7e80-6614-11e9-812a-2c3384bef37a.png)
after
![image](https://user-images.githubusercontent.com/9606042/56587463-2c4af600-6614-11e9-873d-4717b5bb483a.png)

**Comment by soufianesakhi** [comment]
Fixed in v3.13.8
