### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by saputnik** [soufianesakhi/feedly-filtering-and-sorting#65]
My apologies for bothering again, I am really sorry... I noticed that sorting still doesn't work like before, with many articles with a lot of posts high in popularity not sorted correctly (they are not at the top).

**Comment by soufianesakhi** [comment]
If you sort by popularity, there is an additional sorting that occurs 4 seconds after the articles are loaded.
Can you try to wait 4 seconds and check if the sorting happens ?
If not do you see any errors on the console ?

**Comment by saputnik** [comment]
I sort by latest articles, if you mean that, and I have no additional sorting after loading the posts. I don't see errors in the console
![Screenshot 2019-05-03 at 13 03 53](https://user-images.githubusercontent.com/48006970/57131659-bf6af500-6da5-11e9-8ae6-8dfa4c07726a.png)

**Comment by soufianesakhi** [comment]
Can you export your settings and attach them?
Also can you give me some feed (subscription) url that have the problem to test your set up ?

**Comment by saputnik** [comment]
> Can you export your settings and attach them?

Do you mean the OPML?

**Comment by soufianesakhi** [comment]
No via the extension's menu, `Settings controls` tab -> Export settings

**Comment by saputnik** [comment]
I am really embarrassed... I can't find the extension's menu :/

**Comment by soufianesakhi** [comment]
It's on the feedly page next to the refresh button
![](https://raw.githubusercontent.com/soufianesakhi/feedly-filtering-and-sorting/master/screenshots/toggle%20button.PNG)

**Comment by saputnik** [comment]
Thanks! I managed, but I can't attach the json file here. Can I send it to you by email?

**Comment by soufianesakhi** [comment]
Yes: soufiane.sakhi.js@gmail.com

**Comment by soufianesakhi** [comment]
Did you install the latest version of the extension: 3.13.8 ?
If yes, do you see in the browser console these three messages from feedly-filtering-and-sorting.js:
- Sorting articles at <time1>
- forced pop sort
- Sorting articles at <time2>

Is <time2> 4 seconds after <time1> ?

**Comment by saputnik** [comment]
yes, 3.13.8, before this version I never had similar problems.

In the console I see only forced pop sort, no sorting articles at

**Comment by saputnik** [comment]
sorry, my mistake, there is also sorting articles at:

**Comment by soufianesakhi** [comment]
I have implemented an algorithm that checks every 3 seconds if the articles are sorted (when sorting by popularity).
It's available in v3.13.9.
Let me know if it works for you :)

**Comment by saputnik** [comment]
it works perfectly! 

grazie!
