### ISSUE TITLE
forward navigation to a read article broken

### ISSUE THREAD

**Issue by johnpane** [soufianesakhi/feedly-filtering-and-sorting#69]
When I read articles fast I sometimes backtrack. That is, I do a series of "j" commands, followed by one or more "k" to back up and review a previous article, then resume with "j". At the point where I am resuming with "j", there are several already-read articles upcoming before getting to new ones. I still might like to review those. Without Feedly Filtering and Sorting, feedly steps through the read and unread articles one-by-one in both directions ("j" and "k"). However when Feedly Filtering and Sorting is running, it steps through read articles only in the reverse direction ("k"). In the forward direction, it skips them, or if there are no unread articles left, refuses to move at all, reporting "At End". The screen shot shows that last situation.
<img width="1381" alt="Screen Shot 2019-07-05 at 06 20 22" src="https://user-images.githubusercontent.com/14841761/60716661-fb2d5280-9eed-11e9-8975-d3386e460e26.png">

**Comment by soufianesakhi** [comment]
This is worth fixing, I agree

**Comment by soufianesakhi** [comment]
Fixed in v3.13.14

**Comment by johnpane** [comment]
Confirmed fixed! Thank you!
