### ISSUE TITLE
Filter for author

### ISSUE THREAD

**Issue by marcus-at-localhorst** [soufianesakhi/feedly-filtering-and-sorting#7]
Hey, filtering for author would be great too. But then I think the keywords need scopes so if you want to filter for author "admin" on a certain feed, you don't filter headlines with the word "admin" in it

maybe it can be implemented like: `keyword to filter, another, keyword, author:admin istrator, more keywords` So you can split at `:`to find out the scope.

Or have more fields :)

**Comment by soufianesakhi** [comment]
With the 2.4.1 version, you can disable the "Always use these matching areas" in Keyword controls, then there is a select box that will appear to choose the area (scope) where you want to search when adding a keyword.
