### ISSUE TITLE
duplicate detection is generating false positives

### ISSUE THREAD

**Issue by johnpane** [soufianesakhi/feedly-filtering-and-sorting#70]
Duplicate detection is treating certain articles that are not duplicates as duplicates. Screen shot highlights some recent ones, which I have verified are not duplicates. It seems these are situations where there are individual comments in a discussion, where the title is the same (modulo "Re: "). It seems for this to work properly, FFnS may have to look deeper than just the title. Alternatively, it would be helpful to be able to turn it off for certain collections.

<img width="1207" alt="Screen Shot 2019-07-05 at 08 26 05" src="https://user-images.githubusercontent.com/14841761/60722870-199c4980-9f00-11e9-87d5-0c94991c3160.png">

**Comment by soufianesakhi** [comment]
I will try to review your issues as soon as possible

**Comment by johnpane** [comment]
Thank you kindly. No rush.

**Comment by johnpane** [comment]
I think this issue may be solved if I turn off "always use global settings"

**Comment by johnpane** [comment]
I confirm that I can resolve this problem to my satisfaction by using separate settings for discussion feeds like those in my screen shot. I will leave it to you to close the issue, because some might consider false positives for duplicates more difficult to resolve.

**Comment by soufianesakhi** [comment]
Do these discussion feeds have also the same url ? If not I can maybe add an option to do choose to check wether to check duplicates only by title, only by url or both at the same time.
Did you check that duplicate checking is still enabled when you turned off "always use global settings" ?

**Comment by johnpane** [comment]
In one case, "Corner of Ber...", each article has a unique URL.
In the other case, "PixInsight For...", the URLs are not distinct for messages on the same thread.

After I changed the "always use global settings" I set it up so these two feeds do not perform duplicate checking. This solved my problem. I left the feature on for other feeds where this issue is not apparent.

**Comment by soufianesakhi** [comment]
I see. That's the ideal solution for this case. I will close the issue.
