### ISSUE TITLE
Preference panels on Safari with TamperMonkey

### ISSUE THREAD

**Issue by johnpane** [soufianesakhi/feedly-filtering-and-sorting#71]
I am using Safari with FFnS running in TamperMonkey. In this environment, the preference panels do not fully expand to show all the contents, even though there is sufficient window space. Example attached where I have scrolled to the bottom -- also note how this causes the tooltip to be partly obscured.

<img width="1380" alt="Screen Shot 2019-07-05 at 15 36 47" src="https://user-images.githubusercontent.com/14841761/60742416-533e7600-9f3b-11e9-8566-b722c56139f3.png">

**Comment by soufianesakhi** [comment]
Can you try v3.13.14 and see if it fits better ?

**Comment by johnpane** [comment]
Fixed! Thank you!
