### ISSUE TITLE
3.14.0 and settings

### ISSUE THREAD

**Issue by johnpane** [soufianesakhi/feedly-filtering-and-sorting#73]
Hello,

I have accumulated many keywords for filtering. With the update to version 3.14.0, I cannot see these when I go into the settings. It appears as though all the keywords have been lost but if I look into the data storage they are still there. Could the changes in the feed url format have orphaned the settings data?

Thanks,
John

**Comment by soufianesakhi** [comment]
Hello,
Can you check the browser URL when opening of one of your subscription pages in Feedly. Does it start with: https://feedly.com/i/feed/content/feed/ ?

The 'All' page changed it's URL, so if you have specific settings for this special page, you have to import the old settings from the `Settings controls` -> `Subscription management`, by selecting `latest` and clicking `Import settings from selected subscription`

**Comment by johnpane** [comment]
All of my preferences are stored on "collections" of individual feeds, with URLs like this:

https://feedly.com/i/collection/content/user/635bc87e-efa7-405b-b737-b1751b82003e/category/03.%20corner

**Comment by soufianesakhi** [comment]
Can you go to Settings controls -> Subscription management, do you see the `category/03.%20corner` option in the select box ?

**Comment by johnpane** [comment]
Yes, that is there, as well as:
collection/content/user/635bc87e-efa7-405b-b737-b1751b82003e/category/03.%20corner

I think the data are in the one I show here, but now you are using the one you showed?

**Comment by johnpane** [comment]
I see a path towards fixing this by manually importing from the old one to the new one.

**Comment by soufianesakhi** [comment]
Yes that's a possible solution, but normally I have adapted the code to support the new URLs, just make sure that you updated to the 3.14.0 version. Which platform do you use ?

**Comment by johnpane** [comment]
Yes, I am using 3.14.0 via Tampermonkey on Safari.

Also, export settings produces this error:
<img width="700" alt="Screen Shot 2019-08-29 at 08 20 28" src="https://user-images.githubusercontent.com/14841761/63939707-e674c300-ca35-11e9-99b3-05a4bb1258fd.png">

**Comment by johnpane** [comment]
I have successfully moved the data into the newer configuration. Thank you for pointing to this capability.

**Comment by soufianesakhi** [comment]
You're welcome

**Comment by johnpane** [comment]
Just a note that with 3.14.1 I had to re-import the settings for all my feeds again. They were still listed under the old url.

**Comment by soufianesakhi** [comment]
I updated the script in 3.14.1 because Feedly made a change to the url again, I had to decode the URL to get the correct one. Thank you for understanding.
