### ISSUE TITLE
button or hotkey request

### ISSUE THREAD

**Issue by gridan17** [soufianesakhi/feedly-filtering-and-sorting#74]
Hello!
I wonder if it's possible to add a button or a hotkey to quickly enable/ disable checkbox "Filtering enabled", because sometimes I feel I miss sth important with filters?
Or maybe add an option to show hidden articles with another style?
Thank you!

**Comment by soufianesakhi** [comment]
Hi,
Thanks for the suggestion!
I will add a button to disable all filters and thus show all articles

**Comment by gridan17** [comment]
Thank you for a quick feedback and great news!
Wish you all the best!

**Comment by soufianesakhi** [comment]
Added in v3.15.0 (more instructions can be found on the [release notes](https://github.com/soufianesakhi/feedly-filtering-and-sorting/releases/tag/v3.15.0)
