### ISSUE TITLE
Proposed enhancement

### ISSUE THREAD

**Issue by johnpane** [soufianesakhi/feedly-filtering-and-sorting#79]
Feedly advertises the key combination shift+j as implementing "Next source or collection". However, since April 2019 this stopped working in certain situations. I have had extensive interactions with their support team but they have not resolved this.

Specifically, if feedly is currently displaying the Today or All views, issuing the shift+j command does not advance the focus to the next source or collection. It retains the same focus.

Thus, each time FFnS is updated, I patch it with a few lines of code.

I wonder if you might be willing to consider implementing this patch. Most of my code should be pluggable, but something would have to be added to the preferences UI to turn on/off the feature and avoid hard-coding the destination when the features is triggered. (I have it hard-coded to the very first collection in my set...which might be fine as an abstract rule if there is a way for FFnS to determine that destination without asking the user to type it into preferences).

My patches and the approximate line numbers where I insert them are below.

Thank you,
John

Note: 635...003 is an elision of what I think is my UUID for feedly.

1986:
        injectToWindow(["overrideGetNextURI"], this.overrideGetNextURI); // John Pane
2032:
        overrideGetNextURI(); // John Pane
2579:
    FeedlyPage.prototype.overrideGetNextURI = function () { // John Pane
        var navigo = window["streets"].service("navigo");
        var prototype = Object.getPrototypeOf(navigo);
		prototype.getNextURI = function() {
            var e = this.nextURI;
            if ((null == e) || (e == "collection/content/user/635...003e/category/global.all") || (e == "my")) {
                this.nextURI = "collection/content/user/635...003e/category/00.%20edgar";
            }
            return this.nextURI;
        };
    };

**Comment by soufianesakhi** [comment]
Sure, I will add a fix for this

**Comment by johnpane** [comment]
Awesome, thank you!

**Comment by johnpane** [comment]
It may also be possible to patch the data structure that comes from feedly so that the .nextURI field points to the first collection or source (or first with unread articles) . That might avoid the user having to specify a destination.

**Comment by soufianesakhi** [comment]
Added in v3.16.0

**Comment by johnpane** [comment]
Works great! Thank you!

**Comment by soufianesakhi** [comment]
Feature restored in v3.21.0

**Comment by johnpane** [comment]
Broken again by some feedly change this morning.
