### ISSUE TITLE
Hide read items after reading them?

### ISSUE THREAD

**Issue by GokuderaElPsyCongroo** [soufianesakhi/feedly-filtering-and-sorting#8]
Would be great if feeds could disappear after reading them. There already is a "mark as read and hide" button but it is meant for single feeds, so not really useful. Your "mark articles above (or below) as read" button is excellent, is it possible to implement one that hide articles in addition to that ? That would be particularly useful when using the "group hot articles and pin to top" feature : sometimes while loading feeds (when auto-load is disabled), hot articles go on top, above already read articles, which is uncomfortable when they are many. On that script (https://greasyfork.org/en/scripts/2369-feedly-hide-read-items-when-done) someone reported that articles used to disappear when clicking on them to read directly in feedly, problem solved in the update I think. But that 2014 script doesn't work for current version.

My English is weak sorry, I am french.
Your script is very useful thank you!

**Comment by soufianesakhi** [comment]
With v2.5.0: You can now hide entries above/bellow and hide after reading an entry
