### ISSUE TITLE
filter not work for "Popular + Latest" view

### ISSUE THREAD

**Issue by hpso007** [soufianesakhi/feedly-filtering-and-sorting#80]
Filter not work for multiple matching area in "Popular + Latest" view

![image](https://user-images.githubusercontent.com/29673387/67262544-cf070300-f4d7-11e9-939e-848763980b40.png)

![image](https://user-images.githubusercontent.com/29673387/67262601-04abec00-f4d8-11e9-92d7-3ee1b6d65728.png)

**Comment by soufianesakhi** [comment]
It's working for me. Can you give me some examples?

**Comment by soufianesakhi** [comment]
Hello,
I retried to reproduce the issue with no luck (by switching between "Latest" to "Popular + Latest" and adding new keywords, refreshing the page etc.)
I will close the issue.
