### ISSUE TITLE
Disabling all filters just for one or two feeds

### ISSUE THREAD

**Issue by saputnik** [soufianesakhi/feedly-filtering-and-sorting#81]
Hey, I have one request, hope I am not bothering. I would like to exclude just couple of feeds from all filtering done by Feedly Filtering and Sorting. Do you think is that possible? Thank you in any case!

**Comment by soufianesakhi** [comment]
Hello, you can use per subscription settings by unchecking the `Always use global settings` checkbox from the General settings. You can then disable filtering when accessing a feed.

**Comment by saputnik** [comment]
Got it :) Thanks! My idea was anyways to have all most popular posts and the posts of a certain feed (with low popularity) in the same page, I don't know if I was clear enough. With your suggestions it works, but with two different pages open (All Personal Feeds, which I need to have running all the time + the other single feed)
<img width="775" alt="Screenshot 2019-11-11 at 16 28 10" src="https://user-images.githubusercontent.com/48006970/68599168-655b9280-04a0-11ea-831e-57f20501fa4e.png">
<img width="777" alt="Screenshot 2019-11-11 at 16 29 27" src="https://user-images.githubusercontent.com/48006970/68599186-72788180-04a0-11ea-93f6-c00a2d64a4a3.png">



PS: is there any way to support your precious work for this extension? donations through paypal?

**Comment by soufianesakhi** [comment]
I see your point.
That's not currently possible.

You can support the work of this extension through Paypal: http://bit.ly/soufianesakhioss

**Comment by saputnik** [comment]
I see, thank you anyways! Maybe once it will be possible, talk soon :)
