### ISSUE TITLE
feature to hightlight an item with certain author

### ISSUE THREAD

**Issue by mosesnow** [soufianesakhi/feedly-filtering-and-sorting#82]
'Coloring rules to highlight titles' under 'UI control' does't apply 'Matching area (domain)' under 'Keywords control'. I would like to have the feature to hightlight an item with certain author.

**Comment by soufianesakhi** [comment]
Thanks for the suggestion. This was implemented in [v3.17.0](https://github.com/soufianesakhi/feedly-filtering-and-sorting/tree/v3.17.0)
