### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by saputnik** [soufianesakhi/feedly-filtering-and-sorting#83]
Hey, since couple of days I get an error when clicking on an article (see screenshot). Can it be related to the extension?

<img width="634" alt="Screenshot 2020-04-27 at 07 40 38" src="https://user-images.githubusercontent.com/48006970/80339447-f19b1f80-885e-11ea-9ae3-fadd47d8f6a1.png">

**Comment by soufianesakhi** [comment]
Did you test with the extension disabled? Can you open the console and see if there any relating error details / stack trace ?

**Comment by saputnik** [comment]
I checked without the extension and everything works correctly, with the extension enabled I get the error. How do I open the console?

**Comment by soufianesakhi** [comment]
CTRL+SHIFT+J

**Comment by saputnik** [comment]
[feedly.com-1588012215227.log](https://github.com/soufianesakhi/feedly-filtering-and-sorting/files/4541436/feedly.com-1588012215227.log)

**Comment by saputnik** [comment]
is this log what you need?

**Comment by soufianesakhi** [comment]
yes

**Comment by saputnik** [comment]
great. thank you so much for helping again!

**Comment by soufianesakhi** [comment]
Can you disable the auto-load feature and check if there are any errors after reloading the page?

**Comment by soufianesakhi** [comment]
I didn't find the issue yet, but I uploaded a new version where I secured some suspected code. You can try it and if there are any errors, resend me the logs from the console.

**Comment by saputnik** [comment]
Unfortunately I am still having the same issue even after the update. See the log

[feedly.com-1588055824113.log](https://github.com/soufianesakhi/feedly-filtering-and-sorting/files/4543785/feedly.com-1588055824113.log)

**Comment by saputnik** [comment]
Also with auto-load disabled
[feedly.com-1588055955060-noautolod.log](https://github.com/soufianesakhi/feedly-filtering-and-sorting/files/4543792/feedly.com-1588055955060-noautolod.log)

**Comment by soufianesakhi** [comment]
Can you disable the duplicate cross-checking (`Advanced controls` -> Uncheck `Enable cross checking with persistence up to`). I think the local storage area may be filled.

**Comment by saputnik** [comment]
I tried, same issue :( I also removed the extension and installed it again, but to no avail. Without the extension feedly works correctly. Sorry for bothering so much...

**Comment by saputnik** [comment]
[feedly.com-1588090346005.log](https://github.com/soufianesakhi/feedly-filtering-and-sorting/files/4547095/feedly.com-1588090346005.log)

**Comment by soufianesakhi** [comment]
Can you check the Feedly 3 dot menu, and see if you are sorting by `Latest` and have checked `Unread only`?
Are you a pro user?  If so can you check that you don't have any Pro feature like sorting / mute filters enabled?

If you are a pro a still have the error, can you create a new standard account and check if you have any error with the extension enabled?

**Comment by saputnik** [comment]
> Can you check the Feedly 3 dot menu, and see if you are sorting by `Latest` and have checked `Unread only`?

Yep, sorting by latest, unread only checked

> Are you a pro user? If so can you check that you don't have any Pro feature like sorting / mute filters enabled?

I disabled mute filters and sorting, but I have still the same issue


> If you are a pro and still have the error, can you create a new standard account and check if you have any error with the extension enabled?

Let me try

**Comment by saputnik** [comment]
Ok, I found some solution. In Feedly, If I select the option  "All views and enable preview when window > 1600px" in Settings / General / Slider I don't get the mistake. It's not the best (I don't like to have the preview opening like that) but it's fine

**Comment by soufianesakhi** [comment]
That's it! Now I able to reproduce the error! I was always using the slider.
I will shortly fix the issue.

**Comment by saputnik** [comment]
Great, merci, grazie!!!

**Comment by soufianesakhi** [comment]
v3.17.2 was released to fix the issue

**Comment by soufianesakhi** [comment]
Effectively fixed starting from v3.17.4
