### ISSUE TITLE
Having major problems with 3.17.4

### ISSUE THREAD

**Issue by johnpane** [soufianesakhi/feedly-filtering-and-sorting#84]
Hello,

I received version 3.17.4 (Chrome extension) this morning and it is acting incorrectly. If there is only one unread article and I try to read it by clicking on it or using the j/k navigation keys, it instantly disappears without displaying. The attached zip file contains a screen recording.

[Screen Recording 2020-04-30 at 08.10.19.zip](https://github.com/soufianesakhi/feedly-filtering-and-sorting/files/4558176/Screen.Recording.2020-04-30.at.08.10.19.zip)

**Comment by soufianesakhi** [comment]
Thank for your report, you have gone to so much trouble!
This will be fixed in the next version (3.17.5).

**Comment by johnpane** [comment]
Thank **you**. This is a great extension and I appreciate that you maintain it.
