### ISSUE TITLE
Phantom copy of first item in list appears at end of list

### ISSUE THREAD

**Issue by johnpane** [soufianesakhi/feedly-filtering-and-sorting#85]
In the attached screen capture, I hit the j key three times.

There are two items in the list, but after navigating to the second item, a phantom copy of the first item now appears AFTER the second item (it no longer appears in its initial position, so there are still only two items in the list). Hitting the j key a third time does not navigate into this item now next on the list. Feedly reports, "at end of list". 
[Screen Recording 2020-05-01 at 05.48.08.zip](https://github.com/soufianesakhi/feedly-filtering-and-sorting/files/4563289/Screen.Recording.2020-05-01.at.05.48.08.zip)

**Comment by johnpane** [comment]
In longer lists, it becomes apparent that the last and second-to-last item are exchanged when navigating to (what was) the last item.

**Comment by johnpane** [comment]
Another recording.
[Screen Recording 2020-05-01 at 06.07.15.zip](https://github.com/soufianesakhi/feedly-filtering-and-sorting/files/4563413/Screen.Recording.2020-05-01.at.06.07.15.zip)

**Comment by soufianesakhi** [comment]
This is a known implementation detail left as I was trying to fix a blocker issue as quickly as possible. I will try to rethink it once I have more availability.

**Comment by soufianesakhi** [comment]
Should be fixed in v3.17.7
