### ISSUE TITLE
Three UI requests

### ISSUE THREAD

**Issue by johnpane** [soufianesakhi/feedly-filtering-and-sorting#87]
These would make operation smoother for me. I am often tuning my filters.

1. Upon entry into the keywords panes, can the insertion point be placed into the data-entry field?
2. Can enter be a keystroke shortcut for the + (add keyword) button?
3. Can escape be a keystroke shortcut for the X (close) button?

Thank you,
John

**Comment by soufianesakhi** [comment]
This was finally implemented in the latest version!
