### ISSUE TITLE
Extension 

### ISSUE THREAD

**Issue by saputnik** [soufianesakhi/feedly-filtering-and-sorting#88]
The extension stopped working completely this morning. Do you have any idea what happened? Thanks in advance, S.

**Comment by soufianesakhi** [comment]
Thanks for opening the issue 👍 
Indeed there were some code changes by Feedly. I will update the extension accordingly.

**Comment by saputnik** [comment]
Thank you so much!

**Comment by soufianesakhi** [comment]
I have submitted the fix in the latest release.
It's under review for Google Chrome, and available for Firefox & userscripts

**Comment by soufianesakhi** [comment]
It's now available for Google Chrome

**Comment by saputnik** [comment]
everything perfect, thanks!

**Comment by soufianesakhi** [comment]
You're welcome!
