### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by saputnik** [soufianesakhi/feedly-filtering-and-sorting#89]
Hey, again me :/ Anybody else experiencing issues with the extension? Nothing appears after the articles are loaded

**Comment by saputnik** [comment]
<img width="745" alt="Screen Shot 2021-01-12 at 17 53 49" src="https://user-images.githubusercontent.com/48006970/104346012-39ea9280-54ff-11eb-8083-4e6a85057fd6.png">

**Comment by soufianesakhi** [comment]
Try to disable the "Hide duplicates" option. I will try to fix it as soon as possible

**Comment by saputnik** [comment]
Sorry, my mistake! I had the hide duplicates option on; therefore I couldn't see any article. My apologies!

**Comment by soufianesakhi** [comment]
A new version will soon be available containing a fix

**Comment by saputnik** [comment]
Thanks!

**Comment by soufianesakhi** [comment]
The fix should be available now on all platforms
