### ISSUE TITLE
Wish: Colorful Listview

### ISSUE THREAD

**Issue by Ack0** [soufianesakhi/feedly-filtering-and-sorting#9]
Hi!

Can you add this feature[0] as an option?
If you think it does not fit the purpose of the script, I'll understand.

Thanks in advance!

[0] https://greasyfork.org/en/scripts/23185-feedly-colorful-listview-mod

**Comment by soufianesakhi** [comment]
Thanks for the proposition, but I think for all the styling concerns you can use the `Stylish` extension.
- You can for example write a custom stylesheet to change the color of the entries:

    @namespace url(http://www.w3.org/1999/xhtml);


    @-moz-document domain("feedly.com") {
      .list-entries > .entry {
        background-color: rgb(230, 255, 243);
      }
    }

You can change `rgb(230, 255, 243)` with the color of you choice (you can pick one at: http://www.w3schools.com/colors/colors_picker.asp)

- You can also change the whole theme by installing one of the many stylesheets available here: https://userstyles.org/styles/browse/feedly

**Comment by Ack0** [comment]
I know that, but what the userscript linked does is automatically put a different color to each source. Eg: all Gizmodo articles will have a blue background, while all Engadget will have a green background.
This I can't to do with CSS.
But thanks anyway, your script is awesome.

**Comment by soufianesakhi** [comment]
I see. You can still use the script you referenced ? If it's not working I can fork it and fix it.

**Comment by Ack0** [comment]
Yes, the referenced script still works. I just did ask this feature to group it in only one script. But, I understand if you think this is bloat or too many work to do. And I really thank you for wanting to help me with this.

**Comment by soufianesakhi** [comment]
This was added in v2.8.0 (UI controls  => Coloring rules to highlight titles => Keyword source: Source title)
