### ISSUE TITLE
Articles loading when reading

### ISSUE THREAD

**Issue by saputnik** [soufianesakhi/feedly-filtering-and-sorting#90]
With 3.17.12, after the articles are loaded and filtered, I start scrolling and new articles pop up in the list, making reading difficult. I don't know if that's clear...

**Comment by saputnik** [comment]
I can wetransfer a screen recording if you want

**Comment by saputnik** [comment]
I tried also on another computer, same issue. It's almost unusable now, when you read a headline the extension loads other articles and it gets impossible to focus

**Comment by soufianesakhi** [comment]
Can you test the latest version?

**Comment by saputnik** [comment]
Yes! One second

**Comment by saputnik** [comment]
Perfect 👍
