### ISSUE TITLE
3.18.2 Fix article sort did in fact unfix.

### ISSUE THREAD

**Issue by heikoherold** [soufianesakhi/feedly-filtering-and-sorting#91]
Hi, this version broke Source Title sorting for me. Every other kind of sort does still work fine.
Also color by Source title won't color anything anymore. Color by keyword does work.
Firefox 84.0.2 3bit in W10 64bit, add-on installation.
Shall I provide config, logs, something?

And: thanks for your wonderful work!

**Comment by soufianesakhi** [comment]
Hello, thanks for opening the issue. This was fixed and will be available soon :)

**Comment by heikoherold** [comment]
Oh, so I misinterpreted the versioning. Sorry.

**Comment by soufianesakhi** [comment]
No you were right. But it was not working because of some Feedly changes, not from the update itself.
This is fixed now in v3.18.3.
