### ISSUE TITLE
"Mark read/unread" buttons disappeared

### ISSUE THREAD

**Issue by Mornon** [soufianesakhi/feedly-filtering-and-sorting#92]
While in list view, if I over on a feed the "Mark read/unread" buttons appear as usual:

![20210213 133227](https://user-images.githubusercontent.com/21358808/107850079-094c9000-6e00-11eb-892e-1d39066b697d.png)

but if I click on a feed to see the actual content the don't appear anymore, while they used to:

![20210213 133239](https://user-images.githubusercontent.com/21358808/107850083-0fdb0780-6e00-11eb-8577-4b7a7b03d887.png)

Would it be possible to have them back again?

**Comment by soufianesakhi** [comment]
Fixed in the latest version
