### ISSUE TITLE
List

### ISSUE THREAD

**Issue by saputnik** [soufianesakhi/feedly-filtering-and-sorting#93]
Hey! Since couple of days, the extension works correctly, but it shows at the bottom articles without any popularity (see screenshot).
<img width="731" alt="Screen Shot 2021-02-26 at 07 56 06" src="https://user-images.githubusercontent.com/48006970/109266381-49e8d800-7808-11eb-8f2d-3b056f30402b.png">

**Comment by soufianesakhi** [comment]
Hello, this is normal because no popularity means popularity = 0 (this was not changed recently).
Do you mean you didn't have articles with no popularity before ? This is also normal, some articles don't have popularity.

**Comment by saputnik** [comment]
Now it works, sorry! Yep, before articles with no popularity weren’t shown.
