### ISSUE TITLE
Makes the transition to another category

### ISSUE THREAD

**Issue by Detsle** [soufianesakhi/feedly-filtering-and-sorting#94]
After reading **Feeds - All** articles and clicking a button **Mark All As Read**
The extension jumps to the next item. How can I disable this?

Screenshot:
![2021-04-06_20-09-48](https://user-images.githubusercontent.com/22348086/113751002-1efd7800-9714-11eb-925a-52b5619d05b4.gif)

**Comment by soufianesakhi** [comment]
Thanks for opening the issue.
I will fix this once I have more availability.

**Comment by soufianesakhi** [comment]
Fixed in v3.20.1. Let me know if it's not working as expected

**Comment by Detsle** [comment]
Problem still exists

**Comment by soufianesakhi** [comment]
Can you check if you have the same behavior when disabling the extension?

**Comment by Detsle** [comment]
Yes, everything works correctly without the extension.
![qDbHR2R 1](https://user-images.githubusercontent.com/22348086/118128065-1713b080-b403-11eb-974f-610c10d09b2b.gif)

**Comment by soufianesakhi** [comment]
Can you check if it's fixed in v3.20.5?

**Comment by Detsle** [comment]
All perfectly!

**Comment by soufianesakhi** [comment]
This is now fixed in the latest version
