### ISSUE TITLE
Suddenly, around 1800 GMT April 27, the filter icon disappeared

### ISSUE THREAD

**Issue by johnpane** [soufianesakhi/feedly-filtering-and-sorting#96]
This is in Chrome on a Mac. FFnS appears to be active but I cannot access the settings. It was working earlier today.  Screenshot shows "/ (30 hidden entries)"  but the filter icon is missing.

<img width="1239" alt="Screen Shot 2021-04-27 at 14 08 14" src="https://user-images.githubusercontent.com/14841761/116291275-6353c500-a762-11eb-898d-d1b01088031c.png">

**Comment by soufianesakhi** [comment]
Fixed in v3.19.1
