### ISSUE TITLE
FFnS not working today

### ISSUE THREAD

**Issue by johnpane** [soufianesakhi/feedly-filtering-and-sorting#97]
The filter icon appears at the top, and the settings screens open, but features such as filtering are inactive.

Version 3.19.1

**Comment by salmanme** [comment]
I agree. It doesn't seem to be working. (Chrome)

**Comment by johnpane** [comment]
Yes, I should have specified that I am using Chrome v90.0.4430.93 on a Mac.

**Comment by beehiveharvest** [comment]
I can't get it to work either (not filtered).
The time now is 0:02 on Sun, 9 May 2021 US time, but it hasn't been working for about 12 hours.

**Comment by saputnik** [comment]
Same issue here

**Comment by soufianesakhi** [comment]
Hello, v2.0.0 was recently released. Can you check if you still have the issue with the new version? Thanks

**Comment by salmanme** [comment]
> Hello, v3.20.0 was recently released. Can you check if you still have the issue with the new version? Thanks
New version works for me (Chrome user). Thanks a lot.

**Comment by beehiveharvest** [comment]
I have confirmed that filtering works in the new version.
Thank you!

It's hard to keep up with feedly because the specs change so often, but I hope you continue to develop it.

**Comment by johnpane** [comment]
Thank you!

**Comment by johnpane** [comment]
Something still not working right. The filtered articles are hidden but are still being presented when I navigate with the "j" key.

**Comment by saputnik** [comment]
I think I found another issue, I don't know if it's only me. When I click on an article it disappears immediately, see video recording

https://user-images.githubusercontent.com/48006970/117622729-3e544e80-b173-11eb-91f3-1c2904b22759.mov
