### ISSUE TITLE
Mark unread buttons disappeared

### ISSUE THREAD

**Issue by Mornon** [soufianesakhi/feedly-filtering-and-sorting#98]
I'm not sure if this depends on Feedly's upgrade, but the buttons to mark the previous/following feed unread are gone.

I think this happened when Feedly changed the All/Uncategorized categories: until yesterday, when I clicked on a feed while in such categories, it just showed the preview keeping it in place, while today it also move it to another position, like it was published in another date.

**Comment by soufianesakhi** [comment]
Hello, v2.0.0 was recently released. Can you check if you still have the issue with the new version? Thanks

**Comment by Mornon** [comment]
Buttons are back while viewing titles, but are still missing in the preview.

**Comment by soufianesakhi** [comment]
Is the preview the inline frame that appears when clicking an article?

**Comment by Mornon** [comment]
Yes, I meant that; do you need screenshots?

**Comment by soufianesakhi** [comment]
Fixed in v3.20.1

**Comment by Mornon** [comment]
It seems in 3.20.2 the issue reappeared in preview (but not in title).

**Comment by soufianesakhi** [comment]
Can you check if it's fixed in v3.20.5?

**Comment by Mornon** [comment]
It's fixed, thanks.
